export type TipoMensagem = "versiculo" | "salmo" | "reflexao";

export interface Mensagem {
  id: string;
  texto: string;
  referencia: string;
  tipo: TipoMensagem;
   fraseMotivacional?: string;
  resumo?: string;
}

export const CATEGORIAS = [
  "Feliz", "Ansioso", "Triste", "Sozinho", "Agradecido", "Nervoso", "Preciso de esperança", "Preciso de paz", "Preciso de força"
] as const;

export type Categoria = typeof CATEGORIAS[number];

export const MENSAGENS: Record<Categoria, Mensagem[]> = {
  "Feliz": [
    { id: "f1", tipo: "versiculo", texto: "Alegrem-se sempre no Senhor. Novamente direi: alegrem-se!", referencia: "Filipenses 4:4", resumo: "Escrito por Paulo enquanto estava preso em Roma, este versículo é uma das declarações mais impressionantes do Novo Testamento, justamente porque vem de alguém em correntes. Paulo dirige essas palavras à igreja em Filipos, uma comunidade que ele amava profundamente e que enfrentava perseguição e divisões internas. Ao repetir o comando 'alegrem-se', o apóstolo deixa claro que a alegria cristã não é um sentimento passageiro provocado por circunstâncias favoráveis, mas uma decisão espiritual ancorada na fidelidade de Deus. Essa alegria não nega a dor — ela coexiste com ela, oferecendo uma força interior que o mundo não consegue explicar. Ao escolher se alegrar 'no Senhor', deslocamos nosso foco daquilo que muda (problemas, finanças, relacionamentos) para Aquele que nunca muda. É um convite diário a olhar para a cruz e lembrar que a vitória definitiva já foi conquistada." },
    { id: "f2", tipo: "salmo", texto: "Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele.", referencia: "Salmos 118:24", resumo: "O Salmo 118 fazia parte do Hallel egípcio, um conjunto de cânticos recitados em grandes festas judaicas como a Páscoa, celebrando a libertação e a providência de Deus. Este versículo específico é uma resposta de adoração ao reconhecimento de que cada amanhecer é obra das mãos do Criador, não um acaso. Quando declaramos que 'este é o dia que o Senhor fez', estamos afirmando que Deus está no controle do tempo e que cada 24 horas vem com um propósito específico para nós. A alegria aqui não depende da agenda do dia, do clima ou do humor com que acordamos — ela é uma escolha consciente de receber o dia como presente. Esse versículo nos ensina que a gratidão é a porta de entrada para a alegria genuína, e que mesmo dias difíceis carregam misericórdias novas. Ao começarmos a manhã com essa declaração, treinamos nosso coração a procurar Deus nos detalhes." },
    { id: "f4", tipo: "versiculo", texto: "O coração alegre aformoseia o rosto.", referencia: "Provérbios 15:13", resumo: "Os Provérbios são uma coletânea de sabedoria prática atribuída majoritariamente a Salomão, e este versículo expõe uma verdade que a ciência moderna confirma: nosso estado emocional interior molda nossa aparência física. Um coração marcado pela alegria do Senhor irradia leveza, brilho nos olhos e uma expressão acolhedora, enquanto a amargura endurece traços e envelhece. O autor sagrado argumenta que a verdadeira beleza não vem de cosméticos, vestimentas ou aparência cuidada, mas de uma alma que encontrou descanso em Deus. Esse princípio também tem implicações relacionais: pessoas com corações alegres atraem, encorajam e abençoam quem está ao seu redor. Cultivar a alegria espiritual não é vaidade — é mordomia do que Deus colocou em nós. Quando o Espírito Santo enche nosso interior, naturalmente o exterior reflete a luz que recebemos." },
    { id: "f5", tipo: "salmo", texto: "Tu me farás conhecer a vereda da vida, a alegria plena da tua presença.", referencia: "Salmos 16:11", resumo: "Este é um dos salmos messiânicos de Davi, citado por Pedro no dia de Pentecostes como profecia da ressurreição de Cristo. Davi escreve em um momento de profunda intimidade com Deus, declarando que a verdadeira satisfação da alma não está em riqueza, fama ou prazeres terrenos, mas em conhecer pessoalmente o Criador. A expressão 'alegria plena' indica uma felicidade que não tem espaços vazios, que preenche cada canto da existência. A 'vereda da vida' é o caminho estreito de obediência que conduz à comunhão eterna com Deus. Davi entende que prazeres mundanos prometem muito, mas entregam pouco e logo desaparecem; já a alegria da presença de Deus é sólida, crescente e definitiva. Este versículo é um convite a buscar a Deus por Ele mesmo, e não apenas pelos benefícios que Ele oferece — pois Nele está a fonte de toda alegria verdadeira." },
    { id: "f6", tipo: "versiculo", texto: "A alegria do Senhor é a vossa força.", referencia: "Neemias 8:10", resumo: "No contexto da reconstrução dos muros de Jerusalém após o exílio babilônico, o povo de Israel se reuniu para ouvir a leitura pública da Lei de Moisés depois de gerações de afastamento. Ao reconhecerem o quanto haviam falhado, todos começaram a chorar profundamente, dominados pela culpa e pelo peso de seus pecados. Neemias e Esdras então interromperam o lamento com uma verdade libertadora: a alegria que vem de Deus seria justamente o que lhes daria forças para reconstruir suas vidas. Esse versículo nos ensina que a alegria cristã não é ingenuidade nem fuga da realidade — é combustível espiritual. Quando focamos no caráter fiel e amoroso de Deus em vez de nas nossas falhas, ganhamos vigor para enfrentar qualquer reconstrução. A força para perseverar não vem do nosso esforço, mas da celebração diária de quem Deus é." },
    { id: "f7", tipo: "salmo", texto: "Pois tu, Senhor, me alegraste pelos teus feitos; exultarei nas obras das tuas mãos.", referencia: "Salmos 92:4", resumo: "O Salmo 92 era especificamente composto para ser cantado no dia de sábado, um momento dedicado ao descanso e à contemplação da bondade de Deus. O salmista convida o leitor a parar e observar tudo o que Deus já fez — desde a criação do universo até as pequenas providências do dia a dia. A alegria aqui nasce da observação consciente: quanto mais olhamos para as obras de Deus, mais motivos encontramos para celebrar. Esse exercício combate diretamente a ansiedade, que se alimenta de focar no que está faltando ou no que pode dar errado. Ao 'exultar' nas obras das mãos divinas, treinamos nossa memória espiritual a recordar Sua fidelidade passada como garantia de Sua fidelidade futura. É uma adoração baseada em fatos, não em sentimentos, e por isso permanece firme mesmo em dias difíceis." },
    { id: "f8", tipo: "versiculo", texto: "Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.", referencia: "Romanos 12:12", resumo: "Paulo escreve à igreja em Roma, uma comunidade que enfrentaria perseguições intensas nas décadas seguintes, e oferece um tripé essencial para a vida cristã prática. A alegria mencionada aqui não está ancorada nas circunstâncias atuais, mas na esperança certa do que Deus prometeu para o futuro — uma redenção completa em Cristo. Essa esperança não é otimismo vago, mas certeza fundamentada na ressurreição. A paciência na tribulação reconhece que sofrimentos fazem parte da jornada, mas não definem o destino final. E a perseverança na oração é o que mantém os outros dois pilares de pé, pois é no diálogo constante com Deus que recebemos forças renovadas. Juntos, esses três elementos formam um estilo de vida que resiste ao desânimo e celebra cada passo da caminhada da fé, mesmo quando o caminho é árduo." },
    { id: "f9", tipo: "salmo", texto: "Servi ao Senhor com alegria; apresentai-vos a ele com cântico.", referencia: "Salmos 100:2", resumo: "O Salmo 100 é um dos hinos mais conhecidos de adoração coletiva, usado tanto nas cortes do templo quanto nas peregrinações dos fiéis a Jerusalém. Ele estabelece que o serviço a Deus não deve ser pesado, obrigatório ou movido pelo medo, mas marcado pela alegria genuína de quem entende a quem está servindo. O salmista descreve um Deus que é digno de toda celebração — Criador, Pastor e dono de um amor leal que dura para sempre. Quando servimos por dever frio, esgotamos rapidamente; quando servimos por amor e gratidão, a tarefa se torna privilégio. O cântico mencionado representa a postura interior antes de ser uma expressão exterior: é o coração reconhecendo o valor de estar diante de Deus. Esse versículo nos convida a transformar cada ação cotidiana em uma forma de adoração espontânea e leve." },
    { id: "f10", tipo: "versiculo", texto: "Até agora nada pedistes em meu nome; pedi, e recebereis, para que a vossa alegria seja completa.", referencia: "João 16:24", resumo: "Estas palavras de Jesus fazem parte do discurso de despedida aos discípulos, na noite anterior à crucificação, quando Ele os preparava para um novo tempo em que oraria não mais ao Pai presencialmente, mas em Seu nome. Pedir 'em nome de Jesus' significa orar alinhado à vontade, ao caráter e aos propósitos de Cristo, não apenas usar uma fórmula religiosa no final de uma oração. Jesus revela aqui um princípio profundo: Deus deseja se relacionar com seus filhos de forma íntima, recebendo pedidos e respondendo de maneira que a alegria deles transborde. Essa alegria 'completa' é diferente das pequenas satisfações momentâneas — é a plenitude que vem de saber que somos ouvidos e amados. Uma vida de oração ativa cultiva uma alegria que não pode ser abalada por circunstâncias externas." },
  ],
  "Ansioso": [
    { id: "a1", tipo: "versiculo", texto: "Não andem ansiosos por coisa alguma, mas em tudo apresentem seus pedidos a Deus.", referencia: "Filipenses 4:6", resumo: "Paulo escreve este texto da prisão romana, onde, em vez de demonstrar preocupação com seu próprio destino, ensina à igreja de Filipos como vencer a ansiedade. O apóstolo não minimiza o problema — ele oferece um caminho prático: substituir a preocupação pela oração intencional acompanhada de gratidão. A ansiedade prospera quando ruminamos os problemas em silêncio dentro da mente; ela perde força quando verbalizamos esses pesos diante de Deus. Apresentar pedidos 'em tudo' significa que nenhum assunto é pequeno demais ou grande demais para a atenção do Pai. A gratidão mencionada no contexto é essencial: ela nos faz lembrar das vezes em que Deus já cuidou de nós no passado, fortalecendo a confiança no presente. O resultado prometido é a paz que excede todo entendimento, uma serenidade que age como sentinela protegendo coração e mente." },
    { id: "a2", tipo: "versiculo", texto: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.", referencia: "1 Pedro 5:7", resumo: "Pedro escreve esta carta a cristãos espalhados pela Ásia Menor que enfrentavam intensa perseguição e incertezas sobre o futuro. A palavra grega traduzida como 'lançar' descreve a ação de arremessar algo pesado para longe de si, com força e intenção — não é entregar com hesitação, é transferir definitivamente. Pedro contrasta nosso esforço humano de carregar fardos com o cuidado ativo de um Deus que se importa pessoalmente com cada detalhe da nossa vida. A motivação para essa entrega não é apenas alívio emocional, mas o caráter amoroso do Pai: Ele cuida de nós não por obrigação, mas por amor genuíno. Esse cuidado é contínuo e atencioso, semelhante ao de um pastor com suas ovelhas. Ao lançarmos nossa ansiedade em Deus, abrimos espaço interior para receber paz, sabedoria e direção." },
    { id: "a4", tipo: "salmo", texto: "Quando a ansiedade já me dominava, o teu consolo trouxe alívio à minha alma.", referencia: "Salmos 94:19", resumo: "Este salmo é um lamento que mistura clamor por justiça com profunda reflexão pessoal, escrito em um período de opressão sobre o povo de Deus. O autor confessa abertamente que houve momentos em que a ansiedade não era leve, mas dominante — uma multidão de pensamentos angustiantes que ocupavam todo o espaço interior. Esse reconhecimento honesto é importante: a Bíblia não condena quem sente, mas oferece um caminho de cura. O consolo de Deus mencionado aqui não é uma fuga das dificuldades, mas uma presença ativa que entra na tempestade junto com a pessoa. Esse alívio chega de várias formas — pela leitura da Palavra, pela oração, pelo cuidado de irmãos na fé, ou por uma paz inexplicável que invade o coração. O salmista nos ensina que reconhecer a ansiedade e buscar conscientemente o consolo divino é o primeiro passo para a libertação." },
    { id: "a5", tipo: "versiculo", texto: "Quem de vocês, por mais que se preocupe, pode acrescentar uma hora que seja à sua vida?", referencia: "Mateus 6:27", resumo: "Esta pergunta retórica de Jesus faz parte do Sermão do Monte, especificamente em um trecho onde Ele aborda a ansiedade com comida, roupas e necessidades básicas. Jesus usa a lógica de forma quase matemática: a preocupação, por mais intensa que seja, não tem poder algum para mudar o tempo, a saúde ou as circunstâncias da vida. Pelo contrário, estudos modernos confirmam que o estresse crônico encurta a expectativa de vida em vez de aumentá-la. O Mestre não está minimizando os problemas reais que enfrentamos, mas convidando-nos a redirecionar a energia que gastamos com a preocupação para algo produtivo: a confiança em Deus e a ação no presente. Ele aponta para a forma como Deus cuida dos lírios do campo e das aves do céu como prova de que cuidará muito mais de Seus filhos. Trocar a ansiedade pela confiança é uma decisão diária de descanso ativo." },
  ],
  "Triste": [
    { id: "t1", tipo: "versiculo", texto: "O Senhor está perto dos que têm o coração quebrantado.", referencia: "Salmos 34:18", resumo: "Davi escreveu este salmo em um dos períodos mais sombrios de sua vida, quando fugia do rei Saul e precisou fingir loucura diante do rei filisteu Aquis para escapar da morte. Mesmo em circunstâncias humilhantes e desesperadoras, ele descobriu uma verdade transformadora: Deus tem uma proximidade especial com aqueles cujo coração está despedaçado. Ao contrário do que muitas vezes sentimos — que a tristeza nos afasta de Deus — a Bíblia ensina que a dor é justamente o lugar onde Ele mais se aproxima. Deus não despreza lágrimas, não exige sorrisos forçados e não pede que escondamos nossa fragilidade. A frase 'coração quebrantado' descreve alguém quebrado pelo sofrimento ou pela consciência das próprias falhas. Para essas pessoas, Deus oferece uma presença íntima, uma ternura especial e uma esperança que reconstrói por dentro." },
    { id: "t2", tipo: "versiculo", texto: "Bem-aventurados os que choram, pois serão consolados.", referencia: "Mateus 5:4", resumo: "Esta é a segunda das Bem-aventuranças, declaradas por Jesus no Sermão do Monte, e contém uma das maiores inversões de valores ensinadas por Ele. Numa cultura que valoriza força aparente, sucesso e ausência de fraqueza, Jesus declara felizes aqueles que choram. Esse choro pode ter várias dimensões: lamento pelo pecado, dor pela perda de alguém amado, tristeza diante das injustiças do mundo ou angústia espiritual. A promessa não é que o choro será evitado, mas que será respondido com consolo divino — um abraço espiritual que só Deus pode dar. Jesus está dizendo que reconhecer e vivenciar a dor honestamente é, paradoxalmente, o caminho para a verdadeira cura. O consolo prometido começa nesta vida através do Espírito Santo e se completará na eternidade, onde toda lágrima será definitivamente enxugada." },
    { id: "t4", tipo: "salmo", texto: "O choro pode durar uma noite, mas a alegria vem pela manhã.", referencia: "Salmos 30:5", resumo: "Davi compôs este salmo como ação de graças após uma experiência intensa de sofrimento e cura, possivelmente uma doença grave que o levou à beira da morte. A imagem da noite e da manhã é uma das mais poderosas da Escritura para representar o ciclo da dor humana. A noite simboliza períodos de luto, perda, depressão ou trevas espirituais — momentos em que parece que o sofrimento nunca terá fim. Mas o salmista, falando por experiência, garante: existe uma manhã. A dor tem prazo, ainda que esse prazo pareça longo demais enquanto estamos no meio dela. Essa promessa não significa que toda situação será resolvida do nosso jeito, mas que Deus traz alegria mesmo dentro das circunstâncias mais difíceis. A fidelidade dele é como o nascer do sol: certa, pontual e capaz de iluminar até a noite mais escura." },
    { id: "t5", tipo: "versiculo", texto: "Ele enxugará dos seus olhos toda lágrima.", referencia: "Apocalipse 21:4", resumo: "Este versículo está em uma das passagens mais belas e esperançosas de toda a Bíblia, onde João descreve a visão da nova Jerusalém — o estado eterno de comunhão entre Deus e Seu povo. A imagem de Deus pessoalmente enxugando lágrimas é extraordinariamente íntima: não é um ato distante, mas o gesto de um pai cuidadoso que se inclina para cuidar de cada filho. A promessa elimina não apenas o choro, mas suas causas — não haverá mais morte, luto, lamento ou dor. Para quem está atravessando uma tristeza profunda hoje, este versículo oferece uma perspectiva eterna: o sofrimento atual é real, mas é também temporário. Tudo aquilo que parece definitivo nesta vida — perdas, doenças, separações — será desfeito pela mão de Deus na consumação de todas as coisas. Essa esperança transforma a forma como atravessamos a dor presente." },
  ],
  "Sozinho": [
    { id: "s1", tipo: "versiculo", texto: "E eu estarei sempre com vocês, até o fim dos tempos.", referencia: "Mateus 28:20", resumo: "Estas são as últimas palavras registradas por Mateus, ditas por Jesus aos discípulos pouco antes de Sua ascensão ao céu. Imagine o cenário: os discípulos estavam prestes a perder a presença física daquele a quem haviam seguido por três anos, e essa promessa veio como âncora para todo o tempo que viria. A palavra 'sempre' não admite exceções — não há momento, lugar, fase da vida ou circunstância em que Jesus se ausente de Seus seguidores. Essa presença não é simbólica, mas espiritualmente real através do Espírito Santo, que habita em cada cristão. Quando a solidão aperta o peito, esse versículo nos lembra que existe uma companhia constante e fiel ao nosso lado. A promessa se estende 'até o fim dos tempos', cobrindo cada geração, cada cultura e cada situação humana. Você nunca está realmente sozinho, mesmo quando se sente assim." },
    { id: "s2", tipo: "versiculo", texto: "Ele nunca o deixará, nunca o abandonará. Não tenha medo!", referencia: "Deuteronômio 31:8", resumo: "Moisés pronuncia essas palavras a Josué em um momento de transição enorme: o povo de Israel estava prestes a entrar na Terra Prometida sem seu líder histórico, e Josué assumiria a responsabilidade gigantesca de conduzir uma nação inteira. O medo do desconhecido era real, e Moisés não tenta ignorá-lo — ele aponta para a única solução verdadeira: a presença constante de Deus. A repetição 'nunca o deixará, nunca o abandonará' usa uma construção hebraica enfática que poderia ser traduzida como 'de jeito nenhum, em hipótese alguma'. Deus não é como pessoas que mudam de opinião, ficam ocupadas ou se cansam de cuidar. Sua fidelidade não depende do nosso desempenho, mas do Seu caráter imutável. Quando sentimos que ninguém percebe nossa luta, este versículo afirma que o Deus do universo está consciente, presente e ativo na nossa vida." },
    { id: "s4", tipo: "salmo", texto: "Ainda que meu pai e minha mãe me abandonem, o Senhor me acolherá.", referencia: "Salmos 27:10", resumo: "Davi escreve este salmo em um contexto de grande perigo, possivelmente cercado por inimigos, e faz uma das declarações mais ousadas sobre o amor de Deus. Ao mencionar pai e mãe, ele aponta para os relacionamentos humanos mais fundamentais e supostamente inquebráveis — aqueles laços que biologicamente e emocionalmente deveriam ser os mais seguros da vida de uma pessoa. Mesmo reconhecendo que até essas relações podem falhar, ferir ou desaparecer, Davi declara com convicção que o cuidado de Deus é superior e mais constante. Para pessoas que experimentaram abandono familiar, rejeição parental ou traição de pessoas próximas, este versículo oferece um consolo profundo: existe um amor que nunca falhará, um Pai que sempre acolhe. Deus não é um substituto de afetos perdidos, mas a fonte original do amor verdadeiro. Em Seus braços, encontramos identidade, segurança e pertencimento." },
    { id: "s5", tipo: "versiculo", texto: "Não os deixarei órfãos; voltarei para vocês.", referencia: "João 14:18", resumo: "Jesus pronuncia essas palavras durante a Última Ceia, em meio a um longo discurso de despedida em que prepara os discípulos para Sua morte, ressurreição e ascensão. A palavra 'órfãos' carrega um peso enorme no contexto da época: na cultura antiga, ficar sem proteção familiar significava vulnerabilidade total, exclusão social e risco de morte. Jesus reconhece que Sua partida poderia gerar exatamente essa sensação nos discípulos, e antecipa a solução: o envio do Espírito Santo, que é a presença constante de Cristo em cada crente. Quando Ele promete 'voltarei para vocês', se refere tanto à Sua aparição após a ressurreição quanto à habitação permanente do Espírito a partir de Pentecostes. Para quem se sente abandonado, espiritualmente desamparado ou perdido na vida, este versículo é uma garantia poderosa: você tem um Pai presente, um Consolador ativo e uma companhia interior que nunca se ausenta." },
  ],
  "Agradecido": [
    { id: "ag1", tipo: "versiculo", texto: "Dêem graças ao Senhor, porque ele é bom; o seu amor dura para sempre.", referencia: "Salmos 107:1", resumo: "Este versículo abre o Salmo 107, um cântico que celebra a libertação do povo de Israel do exílio babilônico e relata diversas situações em que Deus livrou pessoas em apuros. Ele estabelece dois fundamentos centrais para a gratidão cristã: a bondade essencial de Deus e a permanência eterna do Seu amor. Diferente da gratidão humana que muitas vezes depende de circunstâncias favoráveis, a gratidão bíblica é ancorada em quem Deus é, não no que recebemos. A frase 'o seu amor dura para sempre' aparece como um refrão repetido em vários salmos, reforçando que esse amor é fiel mesmo quando falhamos, ininterrupto mesmo quando nos sentimos distantes, e eterno mesmo quando tudo ao redor muda. Cultivar gratidão diariamente é treinar o coração a reconhecer essa bondade em meio à rotina. Quanto mais agradecemos, mais enxergamos motivos para agradecer." },
    { id: "ag2", tipo: "versiculo", texto: "Deem graças em todas as circunstâncias.", referencia: "1 Tessalonicenses 5:18", resumo: "Paulo escreve à igreja de Tessalônica, uma comunidade jovem que enfrentava perseguições, perdas e incertezas sobre o futuro. Em meio a essas dificuldades, o apóstolo ordena algo aparentemente impossível: dar graças 'em todas as circunstâncias'. É importante notar que ele não diz 'por todas as circunstâncias', mas 'em' todas elas — ou seja, não precisamos agradecer pela tragédia em si, mas podemos agradecer dentro dela, reconhecendo a presença e o cuidado de Deus mesmo no meio do caos. A gratidão nesses momentos funciona como um ato de fé, declarando que confiamos em Deus mesmo sem entender. Pesquisas modernas em psicologia confirmam que a prática consciente de gratidão transforma o cérebro, reduz ansiedade e aumenta o bem-estar. Espiritualmente, ela nos posiciona diante de Deus como filhos confiantes, não como vítimas amargas das circunstâncias." },
    { id: "ag4", tipo: "salmo", texto: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.", referencia: "Salmos 103:2", resumo: "Davi começa este salmo dirigindo-se à própria alma, em um exercício consciente de autoexortação espiritual. Ele entende que o coração humano tem uma tendência natural ao esquecimento — esquecemos rapidamente das bênçãos recebidas e nos fixamos com facilidade nos problemas atuais. Ao listar os benefícios divinos nos versículos seguintes (perdão, cura, redenção, amor, justiça), Davi nos ensina uma prática poderosa: a memória ativa da fidelidade de Deus. Esse exercício combate o desânimo, a ingratidão e a sensação de que Deus está distante. Lembrar dos benefícios passados nos dá fé para o presente e esperança para o futuro. O salmista também nos ensina que a adoração começa por dentro, com uma decisão de chamar a alma à ordem antes que ela seja arrastada pelo barulho das circunstâncias. É um modelo de disciplina espiritual aplicável a qualquer momento do dia." },
    { id: "ag5", tipo: "versiculo", texto: "Toda boa dádiva e todo dom perfeito vêm do alto.", referencia: "Tiago 1:17", resumo: "Tiago, irmão de Jesus e líder da igreja em Jerusalém, escreve esta carta a cristãos espalhados pelo mundo, abordando temas práticos da vida de fé. Neste versículo específico, ele estabelece uma verdade fundamental: tudo aquilo que é genuinamente bom em nossa vida tem origem divina. Não importa se a bênção chega através de uma pessoa, de uma circunstância favorável ou de uma realização pessoal — a fonte última é sempre Deus. Tiago continua descrevendo Deus como o 'Pai das luzes, em quem não há mudança nem sombra de variação', enfatizando que essa generosidade não é esporádica, mas constante e confiável. Essa perspectiva transforma nossa maneira de receber bênçãos: em vez de atribuir tudo à sorte ou ao próprio esforço, reconhecemos a mão amorosa de Deus por trás de cada detalhe. Essa consciência nos torna mais humildes, mais agradecidos e mais generosos com os outros." },
  ],
  "Nervoso": [
    { id: "n1", tipo: "versiculo", texto: "O Senhor é a minha luz e a minha salvação; de quem terei temor?", referencia: "Salmos 27:1", resumo: "Davi escreve este salmo em um período de grande perigo, cercado por inimigos que buscavam destruí-lo, mas ainda assim começa com uma das declarações mais corajosas da Bíblia. Ele usa duas metáforas poderosas para descrever Deus: luz, que dissipa as trevas do medo e da incerteza, e salvação, que indica resgate ativo em situações impossíveis. Ao fazer a pergunta retórica 'de quem terei temor?', Davi não está negando que existem ameaças reais; ele está afirmando que essas ameaças perdem o poder diante de um Deus tão grande. O medo prospera no escuro, em meio à confusão e à sensação de estar sozinho; a presença de Deus elimina exatamente essas três coisas. Para quem está nervoso, ansioso ou enfrentando algo intimidador, este versículo é uma declaração para repetir até que o coração se aquiete. Deus é maior que qualquer ameaça presente." },
    { id: "n2", tipo: "versiculo", texto: "Pois Deus não nos deu espírito de covardia, mas de poder e equilíbrio.", referencia: "2 Timóteo 1:7", resumo: "Paulo escreve esta carta da prisão romana, próximo do fim de sua vida, ao jovem Timóteo, que estava enfrentando dificuldades no ministério em Éfeso e provavelmente sentindo medo da perseguição que se intensificava. O apóstolo o lembra de uma verdade fundamental: o medo paralisante não vem de Deus. O Pai equipa Seus filhos com três recursos espirituais essenciais — poder para agir, amor para servir e domínio próprio para tomar decisões sábias mesmo sob pressão. Esse versículo é especialmente relevante para quem sente nervosismo diante de novos desafios, decisões importantes ou situações fora da zona de conforto. A coragem cristã não é ausência de medo, mas a certeza de que temos recursos divinos para enfrentar o que vem. Ao reconhecer que o pânico não é do Espírito, podemos rejeitá-lo conscientemente e abrir espaço para a calma e a clareza que Deus oferece." },
    { id: "n4", tipo: "salmo", texto: "Em paz me deito e logo pego no sono, pois só tu, Senhor, me fazes viver em segurança.", referencia: "Salmos 4:8", resumo: "Davi compõe este salmo provavelmente durante a rebelião de seu próprio filho Absalão, um dos momentos mais dolorosos e perigosos de sua vida, quando precisou fugir de Jerusalém. Mesmo perseguido, traído por pessoas próximas e cercado de incertezas, ele declara conseguir dormir em paz — não porque seus problemas tinham desaparecido, mas porque sua confiança em Deus era maior do que suas circunstâncias. A insônia muitas vezes nasce do nervosismo de tentar controlar mentalmente o que está fora do nosso alcance. Davi nos ensina que a paz para dormir vem do reconhecimento de que existe um Deus acordado cuidando do mundo. Quando entregamos conscientemente nossos medos antes de deitar, recebemos um descanso restaurador. Esse versículo é uma oração noturna poderosa para quem sofre com nervosismo, ansiedade noturna ou insônia, lembrando que a segurança verdadeira não está nas circunstâncias, mas em Deus." },
    { id: "n5", tipo: "versiculo", texto: "Aquietai-vos e sabei que eu sou Deus.", referencia: "Salmos 46:10", resumo: "O Salmo 46 descreve uma situação de grande turbulência — montanhas tremendo, mares rugindo, nações em guerra — e em meio a esse caos, Deus pronuncia este comando direto e profundo. A palavra hebraica traduzida como 'aquietai-vos' significa literalmente 'soltem, parem de lutar, abaixem as mãos'. É um convite para cessar a agitação interior, abandonar a tentativa de controlar tudo e simplesmente reconhecer quem Deus é. Esse versículo é especialmente poderoso para mentes nervosas que vivem em estado constante de alerta e tentativa de resolver tudo. Quando paramos, respiramos e lembramos que Deus é soberano, a perspectiva muda completamente. Os problemas continuam existindo, mas perdem o tamanho desproporcional que ganharam em nossa imaginação. Deus não pede passividade diante da vida, mas confiança ativa que descansa em Sua soberania enquanto agimos no que é nossa responsabilidade." },
  ],
  "Preciso de esperança": [
    { id: "e1", tipo: "versiculo", texto: "Pois eu bem sei os planos que tenho para vocês, planos de dar a vocês esperança.", referencia: "Jeremias 29:11", resumo: "Este versículo foi escrito pelo profeta Jeremias em uma carta enviada aos judeus que estavam exilados em Babilônia, longe de sua terra, separados do templo e enfrentando uma realidade dura e aparentemente sem futuro. O contexto é fundamental: Deus não estava prometendo uma vida fácil ou uma solução imediata, mas garantindo que mesmo no meio do exílio existia um plano divino em andamento. A palavra 'planos' está no plural e indica intencionalidade, propósito e cuidado nos detalhes — Deus não improvisa com nossa vida. Esses planos têm como objetivo trazer esperança e um futuro, mesmo quando o presente parece insuportável. Para quem está vivendo seu próprio 'exílio' — em um momento difícil, distante de onde gostaria de estar — este versículo afirma que Deus enxerga o quadro completo. O que parece o fim pode ser, na verdade, parte de uma jornada maior conduzida por mãos amorosas e sábias." },
    { id: "e2", tipo: "versiculo", texto: "Mas aqueles que esperam no Senhor renovam as suas forças.", referencia: "Isaías 40:31", resumo: "Isaías escreve essas palavras a um povo cansado, derrotado e desanimado, anunciando uma promessa de restauração espiritual e física. O verbo 'esperar' aqui carrega um sentido muito mais profundo do que apenas aguardar passivamente; em hebraico, indica entrelaçar-se com Deus, ancorar a alma Nele em uma atitude de confiança ativa. Quem espera no Senhor recebe uma renovação sobrenatural de forças, descrita em três imagens poderosas: subir como águia (visão elevada e nova perspectiva), correr sem se cansar (perseverança em fases longas de esforço) e caminhar sem se fatigar (constância no dia a dia). A esperança bíblica não é otimismo ingênuo, mas certeza fundamentada no caráter fiel de Deus. Quando estamos exaustos emocional, física ou espiritualmente, este versículo aponta para a fonte verdadeira de renovação: não está em fórmulas mágicas, mas em uma comunhão consciente e contínua com o Senhor." },
    { id: "e4", tipo: "salmo", texto: "Por que você está assim tão triste, ó minha alma? Ponha a sua esperança em Deus!", referencia: "Salmos 42:11", resumo: "O autor deste salmo, possivelmente um dos descendentes de Coré que servia no templo, encontra-se afastado de Jerusalém, sofrendo emocionalmente e sentindo a ausência da adoração comunitária. Em vez de afundar na tristeza, ele faz algo profundamente terapêutico: dialoga com a própria alma, questionando seu desânimo e redirecionando-a para Deus. Essa autoexortação é um modelo poderoso de combate ao desânimo — não negamos os sentimentos, mas também não permitimos que eles tenham a última palavra. Colocar esperança em Deus é uma decisão consciente que reorienta o coração para a fonte certa de descanso. O salmista repete esse refrão ao longo do salmo, mostrando que essa luta interior pode ser longa e exigir várias rodadas de redirecionamento. Para quem sente o peso da tristeza, este versículo ensina que a esperança é também uma disciplina espiritual, cultivada na prática diária de falar verdades à própria alma." },
    { id: "e5", tipo: "versiculo", texto: "A esperança não nos decepciona, porque Deus derramou seu amor em nossos corações.", referencia: "Romanos 5:5", resumo: "Paulo escreve à igreja em Roma desenvolvendo uma das passagens mais profundas sobre a vida cristã, em que mostra como tribulações produzem perseverança, perseverança gera caráter, e caráter produz esperança. Esse processo culmina em uma esperança que não decepciona — uma garantia poderosa, pois muitas esperanças humanas falham. A razão dessa segurança é o amor de Deus derramado em nossos corações pelo Espírito Santo, ou seja, não é uma esperança baseada em sentimentos ou previsões, mas em uma experiência interior real do amor divino. Esse derramamento é generoso, contínuo e transformador, capaz de sustentar a fé mesmo nas piores tempestades. Diferente das promessas humanas que podem quebrar, a esperança fundamentada no amor de Deus é blindada por Sua própria fidelidade. Quem experimentou esse amor encontra coragem para esperar com confiança até mesmo em situações que parecem sem saída." },
  ],
  "Preciso de paz": [
    { id: "p1", tipo: "versiculo", texto: "Deixo-lhes a paz; a minha paz lhes dou.", referencia: "João 14:27", resumo: "Jesus pronuncia essas palavras durante a Última Ceia, sabendo que em poucas horas seria preso, julgado e crucificado. Mesmo diante desse cenário, Ele oferece aos discípulos um presente extraordinário: Sua própria paz. Ele faz questão de diferenciar essa paz daquela que o mundo oferece — a paz mundana depende da ausência de problemas, de circunstâncias favoráveis ou de distrações temporárias. A paz de Cristo, ao contrário, coexiste com tempestades, dores e incertezas. É uma calma profunda que vem de dentro, ancorada na soberania de Deus e na certeza de que tudo está sob Seu controle. Jesus continua dizendo 'não se turbe o vosso coração, nem se atemorize', demonstrando que essa paz é também uma escolha de não permitir que o medo domine. Para quem precisa de paz hoje, este versículo é um lembrete de que ela já foi oferecida — basta receber e descansar nela." },
    { id: "p2", tipo: "versiculo", texto: "Tu, Senhor, guardarás em perfeita paz aquele cujo propósito está firme.", referencia: "Isaías 26:3", resumo: "Isaías escreve esta declaração em um trecho conhecido como o 'cântico de Judá', celebrando a fidelidade de Deus em meio a tempos turbulentos. A expressão 'perfeita paz' no hebraico original é 'shalom shalom' — a palavra repetida para enfatizar uma paz completa, integral, que abrange corpo, alma e espírito. A condição para receber essa paz é específica: ter o propósito (a mente, o pensamento) firmado em Deus. Em uma era de constante distração, ansiedade digital e bombardeio de informações, manter a mente focada em Deus se torna um desafio diário, mas também o segredo da serenidade. Esse foco não exige isolamento do mundo, mas uma decisão consciente de retornar continuamente a quem Deus é, especialmente quando os pensamentos começam a se dispersar. A paz não é fruto da meditação genérica, mas do contato real com o Deus vivo, cuja presença acalma até as mentes mais agitadas." },
    { id: "p4", tipo: "salmo", texto: "O Senhor abençoa o seu povo com paz.", referencia: "Salmos 29:11", resumo: "O Salmo 29 é uma poderosa descrição da voz de Deus manifestada na natureza — trovões, tempestades, raios partindo cedros e fazendo a terra tremer. Depois de descrever toda essa demonstração de poder cósmico, o salmista conclui de forma surpreendente: esse mesmo Deus que governa as tempestades abençoa Seu povo com paz. O contraste é intencional e profundo. O Deus que tem poder para sacudir o universo escolhe, em Sua bondade, sussurrar paz no coração de Seus filhos. Essa paz não é uma esperança vaga, mas uma bênção ativa derramada sobre os que pertencem a Ele. Quando estamos diante de problemas que parecem grandes demais, é importante lembrar que servimos a um Deus muito maior, e que o mesmo braço que controla a criação também sustenta nosso coração. A paz é parte da herança espiritual do crente, oferecida diariamente como sinal do cuidado divino." },
    { id: "p5", tipo: "versiculo", texto: "E a paz de Deus, que excede todo o entendimento, guardará os seus corações.", referencia: "Filipenses 4:7", resumo: "Paulo continua aqui o ensinamento iniciado no versículo anterior, onde orienta os cristãos a substituírem a ansiedade pela oração com gratidão. A resposta de Deus a essa entrega é descrita como uma paz que 'excede todo o entendimento' — ou seja, uma calma que não tem explicação racional diante das circunstâncias. Pessoas ao redor podem se admirar de vê-lo sereno em situações que justificariam pânico, e essa serenidade é justamente o testemunho da paz divina em ação. A imagem de 'guardar' o coração usa uma palavra militar grega que descreve sentinelas vigiando uma cidade — a paz de Deus age como guardiã ativa, impedindo que medo, ansiedade e pensamentos destrutivos invadam nossa mente. Essa proteção acontece 'em Cristo Jesus', ou seja, dentro do relacionamento vivo com Ele. Quanto mais próximos de Cristo, mais essa paz se manifesta como característica natural da nossa vida." },
  ],
  "Preciso de força": [
    { id: "f1_forca", tipo: "versiculo", texto: "Tudo posso naquele que me fortalece.", referencia: "Filipenses 4:13", resumo: "Este é um dos versículos mais conhecidos da Bíblia, mas também um dos mais mal interpretados. Paulo o escreve da prisão, em um contexto específico: ele estava explicando que havia aprendido o segredo de viver contente em qualquer circunstância — tanto na abundância quanto na escassez, tanto com saúde quanto com doença, tanto livre quanto preso. O 'tudo posso' não é uma promessa genérica de sucesso em qualquer empreitada, mas a certeza de que existe força sobrenatural disponível para enfrentar tudo o que a vida traz. Cristo é a fonte dessa capacidade, e a chave está em depender Dele de forma consciente. Quando estamos no limite das nossas forças humanas, este versículo nos lembra que ainda existe uma reserva infinita à nossa disposição. A força cristã não está em negar nossa fraqueza, mas em conectar nossa fragilidade ao poder ilimitado de Cristo." },
    { id: "f2_forca", tipo: "salmo", texto: "O Senhor é a minha força e o meu escudo; nele o meu coração confia.", referencia: "Salmos 28:7", resumo: "Davi escreve este salmo em uma situação de grande angústia, possivelmente cercado por inimigos e clamando para que Deus não o ignorasse. A declaração que se segue é uma das mais ricas em imagens de proteção: o Senhor é simultaneamente força (capacidade interior para enfrentar) e escudo (proteção exterior contra ataques). Davi combina essas duas dimensões para mostrar que Deus cuida do crente por dentro e por fora. A confiança mencionada é uma postura ativa do coração, não apenas um pensamento mental. Quando Davi diz 'nele o meu coração confia', ele indica uma entrega completa, uma dependência total. O resultado dessa confiança aparece no restante do versículo: alegria que transborda em cânticos de gratidão. Para quem precisa de força hoje, este versículo ensina que ela não vem da autoconfiança, mas da decisão consciente de descansar em Deus como suporte e proteção." },
    { id: "f4", tipo: "versiculo", texto: "O Senhor dá força ao seu povo.", referencia: "Salmos 29:11", resumo: "Este versículo conclui o Salmo 29, um cântico majestoso que descreve o poder de Deus manifestado nas tempestades, nos trovões e na própria criação. Depois de mostrar a grandeza cósmica do Senhor, o salmista faz uma transição íntima e pessoal: esse mesmo Deus, que governa os elementos, partilha Sua força com Seu povo. Essa força não é fabricada por nós nem conquistada por esforço próprio — é dada como presente contínuo, um suprimento divino que renova quem dele depende. A palavra 'dá' no original indica uma ação constante, não pontual; é uma fonte que jorra sempre, não um reservatório que se esgota. Para quem está exausto, sobrecarregado ou enfrentando responsabilidades além do que parece suportar, este versículo é uma promessa transformadora. Não precisamos viver da nossa própria força limitada; podemos receber diariamente a força sobrenatural de Deus para cumprir o que Ele nos chamou a fazer." },
    { id: "f5", tipo: "versiculo", texto: "A minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza.", referencia: "2 Coríntios 12:9", resumo: "Paulo escreve aos coríntios sobre um 'espinho na carne' — algo que provavelmente era uma condição física ou espiritual persistente que o incomodava profundamente. Ele orou três vezes pedindo a remoção desse sofrimento, mas Deus respondeu de forma surpreendente: não removeria o problema, mas daria graça suficiente para suportá-lo. Mais ainda, Deus revelou um princípio espiritual revolucionário: é exatamente na fraqueza humana que o poder divino se manifesta com mais clareza. Quando estamos no auge da nossa força, tendemos a confiar em nós mesmos; quando nos reconhecemos frágeis, abrimos espaço para Deus agir. Essa verdade transforma a maneira como enxergamos nossas limitações — elas deixam de ser apenas obstáculos e se tornam oportunidades para experimentar a graça divina de forma palpável. Para quem se sente fraco hoje, este versículo é uma boa notícia: sua fraqueza não é um problema para Deus, é o cenário ideal para Sua atuação." },
  ]
};

// Sistema de Cache Local Requisitado
interface Cache {
  lastMessages: string[];
  lastType: TipoMensagem | null;
}

// O cache deve ser resetado ao fechar/abrir o app (instância em memória)
const cache: Cache = {
  lastMessages: [],
  lastType: null,
};

export function getRandomIdForCategoria(categoria: Categoria): string {
  const todas = MENSAGENS[categoria];
  
  // 1. Remover mensagens exibidas nas últimas 5 interações (cache local na memória do cliente)
  let filtradas = todas.filter(m => !cache.lastMessages.includes(m.id));
  
  if (filtradas.length === 0) {
    cache.lastMessages = [];
    filtradas = todas;
  }

  // 2. Garantir que não apareça o mesmo tipo duas vezes seguidas
  let finalistas = filtradas.filter(m => m.tipo !== cache.lastType);

  if (finalistas.length === 0) {
    finalistas = filtradas;
  }

  // 3. Selecionar aleatoriamente
  const selecionada = finalistas[Math.floor(Math.random() * finalistas.length)];

  // Atualizar cache (isso acontece no cliente antes de navegar)
  cache.lastMessages = [...cache.lastMessages, selecionada.id].slice(-25);
  cache.lastType = selecionada.tipo;

  return selecionada.id;
}

export function getMensagemById(categoria: Categoria, id: string): Mensagem {
  const todas = MENSAGENS[categoria];
  return todas.find(m => m.id === id) || todas[0];
}

export function getProximaMensagem(categoria: Categoria): Mensagem {
  const id = getRandomIdForCategoria(categoria);
  return getMensagemById(categoria, id);
}
