export interface Devocional {
  versiculo: string;
  referencia: string;
  dica: string;
  reflexao: string;
  pergunta: string;
  oracao: string;
}

export const DEVOCIONAIS: Devocional[] = [
  {
    versiculo: "Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.",
    referencia: "Salmos 37:5",
    dica: "Antes de começar, respire fundo três vezes. Solte os ombros. Deixe o celular longe do olhar por três minutos.",
    reflexao: "Entregar não é largar tudo no ar; é depositar nas mãos de Alguém confiável. Quando confio em Deus, meus planos deixam de ser fardos e viram oferta. Ele não promete que tudo vai como eu queria, mas que Ele vai fazer o melhor pra mim.",
    pergunta: "O que você está tentando controlar sozinho hoje e precisa entregar?",
    oracao: "Senhor, hoje eu solto o que não é meu pra carregar. Entrego meus planos, meus medos e meus dias nas Tuas mãos. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.",
    referencia: "Isaías 41:10",
    dica: "Pare por um instante. Feche os olhos. Sinta o peso do corpo na cadeira. Deus está aqui.",
    reflexao: "Deus não diz 'não sinta medo'; Ele diz 'não temas, porque Eu estou'. A diferença é a presença. O medo perde força quando lembro que não estou sozinho pra enfrentar o que vem.",
    pergunta: "Onde o medo tem te paralisado ultimamente?",
    oracao: "Pai, obrigado por não me deixar sozinho. Toma o meu medo e coloca no lugar a Tua paz. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos aliviarei.",
    referencia: "Mateus 11:28",
    dica: "Respire devagar. Inspire por 4 segundos, segure por 4, solte por 6. Repita duas vezes.",
    reflexao: "Jesus não chamou os fortes ou os que têm tudo resolvido. Chamou os cansados. Isso significa que o cansaço, longe de te afastar dEle, é o convite mais direto pra chegar perto.",
    pergunta: "O que está pesando demais no seu coração agora?",
    oracao: "Jesus, eu venho como estou. Descanso em Ti o que me esgota. Renova as minhas forças. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Buscai primeiro o Reino de Deus, e a sua justiça, e todas as coisas vos serão acrescentadas.",
    referencia: "Mateus 6:33",
    dica: "Antes de ler, faça uma lista mental do que ocupa seu coração hoje. Coloque essa lista de lado por 3 minutos.",
    reflexao: "Buscar primeiro não é buscar só. É uma questão de ordem. Quando Deus ocupa o primeiro lugar, o resto encontra o lugar certo. Quando as outras coisas viram prioridade, elas viram peso.",
    pergunta: "O que tem tomado o primeiro lugar dentro de você essa semana?",
    oracao: "Senhor, coloca no meu coração o desejo de Te buscar antes de tudo. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O Senhor é o meu pastor; nada me faltará.",
    referencia: "Salmos 23:1",
    dica: "Leia o versículo em voz baixa, três vezes. A cada leitura, sublinhe uma palavra diferente com a mente.",
    reflexao: "O pastor conhece cada ovelha, sabe onde tem pasto e onde tem perigo. Dizer 'nada me faltará' não é ingenuidade; é confiar em Quem já provou que sabe cuidar.",
    pergunta: "Em que área da sua vida você precisa lembrar que Deus já está cuidando?",
    oracao: "Bom Pastor, obrigado por conhecer cada uma das minhas necessidades. Ensina-me a descansar no Teu cuidado. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Alegrai-vos sempre. Orai sem cessar. Em tudo dai graças.",
    referencia: "1 Tessalonicenses 5:16-18",
    dica: "Antes de continuar, lembre-se de três coisas boas que aconteceram nas últimas 24 horas. Nomeie mentalmente.",
    reflexao: "Gratidão não é fingir que está tudo bem. É treinar o olhar pra ver a bondade de Deus mesmo no que é pequeno. Quem agradece muda o clima do próprio coração.",
    pergunta: "Pelo que, mesmo pequeno, você pode agradecer agora mesmo?",
    oracao: "Pai, hoje eu escolho ver a Tua bondade nos detalhes. Que a gratidão me acompanhe o dia todo. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Bem-aventurados os que têm limpo o coração, porque eles verão a Deus.",
    referencia: "Mateus 5:8",
    dica: "Silencie o celular. Respire fundo uma vez. Peça a Deus, em silêncio, que sonde o seu coração agora.",
    reflexao: "Um coração limpo não é um coração perfeito; é um coração honesto, sem esconderijos. Deus se revela pra quem não finge ser o que não é.",
    pergunta: "Existe algo que Deus tem pedido pra você largar pra andar mais leve com Ele?",
    oracao: "Senhor, sonda o meu coração. Purifica o que me afasta de Ti. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo.",
    referencia: "Salmos 23:4",
    dica: "Feche os olhos. Imagine Deus caminhando literalmente ao seu lado no momento mais difícil da sua semana.",
    reflexao: "Davi não diz que o vale desaparece; diz que atravessa com companhia. A promessa não é ausência de dor, mas presença de Deus dentro dela.",
    pergunta: "Qual 'vale' você está atravessando agora, e o que muda em saber que Ele vai junto?",
    oracao: "Senhor, atravessa comigo o que eu tenho medo de atravessar sozinho. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Tudo posso naquele que me fortalece.",
    referencia: "Filipenses 4:13",
    dica: "Sente com a coluna reta. Sinta a força do chão sob seus pés. Essa é a base. Deus é a sua.",
    reflexao: "Paulo escreveu isso preso, sem nada. Não é uma promessa de sucesso em tudo, é a certeza de que aguento tudo em Cristo. Força que vem dEle não falha, mesmo quando a minha acaba.",
    pergunta: "Onde você precisa hoje da força que não é sua?",
    oracao: "Cristo, sê a minha força hoje onde a minha acaba. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O Senhor pelejará por vós, e vós vos calareis.",
    referencia: "Êxodo 14:14",
    dica: "Faça silêncio por trinta segundos antes de continuar. Só ouça.",
    reflexao: "Deus não pede que eu resolva tudo com palavras ou reações. Às vezes o mais espiritual é ficar quieto e deixar Ele agir. Silêncio confiante é oração.",
    pergunta: "Em que situação você está falando demais e confiando de menos?",
    oracao: "Senhor, cala o meu barulho interno. Peleja por mim. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Aquietai-vos e sabei que eu sou Deus.",
    referencia: "Salmos 46:10",
    dica: "Antes de ler, escolha uma posição confortável e não mexa o corpo por um minuto. Só respire.",
    reflexao: "Aquietar é rebelião contra o barulho do mundo. Só quem para consegue lembrar de novo Quem é Deus. E quem lembra, deixa de ter medo.",
    pergunta: "O que hoje está te impedindo de aquietar?",
    oracao: "Deus, aquieta o que ferve aqui dentro. Lembra-me de quem Tu és. Em nome de Jesus, amém.",
  },
  {
    versiculo: "As misericórdias do Senhor se renovam a cada manhã.",
    referencia: "Lamentações 3:22-23",
    dica: "Se você errou ontem, deixe ali. Este momento é novo. A misericórdia é fresca.",
    reflexao: "Não preciso carregar o peso do ontem pra dentro do hoje. Deus não guarda escândalo. A cada manhã, Ele me olha novo. Isso é gentileza divina.",
    pergunta: "O que do ontem você precisa deixar ir, agora, pra viver o hoje?",
    oracao: "Pai, obrigado pela misericórdia nova. Recebo o hoje pela Tua graça. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Lança sobre o Senhor os teus cuidados, e ele te susterá.",
    referencia: "Salmos 55:22",
    dica: "Nomeie mentalmente um cuidado que está te consumindo. Imagine que você o coloca numa cesta e entrega.",
    reflexao: "Lançar tem gesto: exige movimento. Preocupação parada vira ansiedade. Preocupação entregue vira oração. Deus recebe o que eu solto.",
    pergunta: "Qual preocupação hoje você precisa lançar em vez de segurar?",
    oracao: "Senhor, lanço o que me pesa sobre Ti. Sustenta-me. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O choro pode durar uma noite, mas a alegria vem pela manhã.",
    referencia: "Salmos 30:5",
    dica: "Se você está triste agora, não force sorriso. Só respire e leia devagar.",
    reflexao: "A noite tem hora pra acabar. Deus não promete pular o choro; promete que ele não tem a palavra final. Depois dele, vem manhã. Depois dela, dia.",
    pergunta: "Em qual 'noite' você está agora, e do que você precisa lembrar sobre a manhã que vem?",
    oracao: "Pai, sustenta-me nesta noite. Aguardo a Tua manhã. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Eu vim para que tenham vida e a tenham em abundância.",
    referencia: "João 10:10",
    dica: "Pense num momento nos últimos dias em que você se sentiu vivo. Agradeça em silêncio.",
    reflexao: "Vida abundante não é vida perfeita. É vida com Cristo dentro. Ele não veio pra encher a agenda, veio pra encher a alma.",
    pergunta: "Onde na sua semana você tem trocado vida por rotina, e como Deus pode restaurar isso?",
    oracao: "Jesus, enche a minha vida da Tua vida. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.",
    referencia: "Romanos 8:28",
    dica: "Lembre de uma coisa difícil no seu passado que hoje faz sentido. Deus estava ali.",
    reflexao: "'Todas' inclui o que dói. Não é que tudo é bom; é que Deus tece até o feio pra bem. Meu papel é confiar, mesmo sem enxergar ainda o desenho pronto.",
    pergunta: "Que 'linha torta' na sua vida você precisa entregar pra Deus escrever direito?",
    oracao: "Deus, confio que Tu tramas bem até o que não parece. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Se, pois, o Filho vos libertar, verdadeiramente sereis livres.",
    referencia: "João 8:36",
    dica: "Nomeie mentalmente uma coisa que te prende. Só nomeie, sem julgar.",
    reflexao: "Liberdade não é fazer o que quero; é não ser mais escravo do que me destrói. Cristo liberta de dentro pra fora, e essa liberdade dura.",
    pergunta: "De qual corrente você precisa que Cristo te liberte hoje?",
    oracao: "Jesus, quebra o que me prende. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.",
    referencia: "Salmos 46:1",
    dica: "Coloque a mão sobre o peito. Sinta a batida. Deus é 'bem presente', tão perto quanto isso.",
    reflexao: "Refúgio é lugar onde eu corro. Fortaleza é lugar onde eu fico. Deus é os dois. Nas horas ruins, não preciso procurar longe; Ele já está.",
    pergunta: "De qual angústia você precisa correr pra Deus hoje?",
    oracao: "Senhor, meu refúgio, corro pra Ti. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.",
    referencia: "Isaías 40:31",
    dica: "Respire fundo três vezes, alongando os braços. Deus renova quem espera.",
    reflexao: "Esperar não é passivo. É confiar ativamente que Deus vem. E quem espera dEle não cansa como cansa quem depende de si mesmo. Ele repõe o que o dia gastou.",
    pergunta: "Onde a sua força acabou, e o que muda em esperar em Deus em vez de tentar mais?",
    oracao: "Senhor, renova as minhas forças. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O amor de Deus é derramado em nossos corações pelo Espírito Santo.",
    referencia: "Romanos 5:5",
    dica: "Feche os olhos. Imagine o amor de Deus como algo derramado devagar dentro do peito.",
    reflexao: "O amor de Deus não é ideia; é presença. Ele foi derramado, ou seja, entrou de fato dentro de mim. Eu já sou amado antes de fazer qualquer coisa por Ele.",
    pergunta: "Você tem tentado ganhar o amor de Deus, quando Ele já foi derramado em você?",
    oracao: "Pai, obrigado pelo Teu amor derramado em mim. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.",
    referencia: "Provérbios 3:5",
    dica: "Solte a mandíbula. Solte os ombros. O corpo mostra quando a mente está tentando resolver tudo sozinha.",
    reflexao: "'De todo o coração' significa não guardar uma parte pra minhas próprias apostas. É confiança sem plano B. É difícil, mas é onde a paz mora.",
    pergunta: "Em qual decisão você está confiando mais no seu entendimento do que em Deus?",
    oracao: "Senhor, confio em Ti mais do que na minha cabeça. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Bem-aventurados os mansos, porque eles herdarão a terra.",
    referencia: "Mateus 5:5",
    dica: "Antes de responder qualquer pessoa hoje, respire uma vez. A mansidão começa aí.",
    reflexao: "Manso não é fraco. É forte com autocontrole. É saber que não precisa provar nada porque Deus já defende. A mansidão desarma quem espera briga.",
    pergunta: "Com quem hoje você precisa reagir com mansidão em vez de dureza?",
    oracao: "Espírito Santo, ensina-me a ser manso. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Bem-aventurados os que choram, porque eles serão consolados.",
    referencia: "Mateus 5:4",
    dica: "Se veio uma lágrima, deixe cair. Chorar diante de Deus também é oração.",
    reflexao: "Jesus não disse 'não chore'. Ele chamou de bem-aventurado quem chora, porque só chora quem se importa. E Deus consola quem chora nEle.",
    pergunta: "Existe uma dor que você não deu espaço pra chorar diante de Deus?",
    oracao: "Pai, choro diante de Ti. Consola o meu coração. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.",
    referencia: "Mateus 5:6",
    dica: "Pense: o que sua alma tem tido fome ultimamente?",
    reflexao: "Fome de justiça é querer ver o certo prevalecer, em mim primeiro. Deus promete saciar quem procura viver reto. Ele não deixa vazio quem busca sério.",
    pergunta: "Onde você anda com fome do certo e cansado do errado?",
    oracao: "Deus, sacia essa fome de viver o que é reto. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me.",
    referencia: "Mateus 16:24",
    dica: "Considere: o que é 'a minha cruz' hoje? Não é sofrimento por sofrer. É o fardo do caminho com Cristo.",
    reflexao: "Seguir Jesus tem custo. Mas o peso da cruz é sempre menor do que o peso de viver longe dEle. Negar-se é dizer sim ao que é maior.",
    pergunta: "O que você precisa 'negar' em você mesmo hoje pra seguir Jesus mais de perto?",
    oracao: "Jesus, ensina-me a Te seguir hoje. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Deus não nos deu espírito de covardia, mas de poder, de amor e de moderação.",
    referencia: "2 Timóteo 1:7",
    dica: "Endireite a coluna. O corpo em posição de coragem ajuda o coração a lembrar.",
    reflexao: "O medo grita, mas nem sempre diz a verdade. Deus me deu outro espírito: força pra enfrentar, amor pra não machucar e equilíbrio pra não exagerar.",
    pergunta: "Onde a covardia tem falado mais alto do que a fé em você?",
    oracao: "Senhor, cala a covardia. Enche-me do Teu Espírito. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Perto está o Senhor dos que têm o coração quebrantado.",
    referencia: "Salmos 34:18",
    dica: "Coloque a mão sobre o peito. Sinta. Deus se aproxima justamente aí.",
    reflexao: "Quebrantado não é fracassado. É consciente da própria condição. É quem sabe que precisa. Nesse coração, Deus tem prazer em morar.",
    pergunta: "Você tem escondido de Deus onde o seu coração está quebrado?",
    oracao: "Pai, chega perto do que em mim está quebrado. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Eu sou a videira; vós, os ramos. Sem mim nada podeis fazer.",
    referencia: "João 15:5",
    dica: "Imagine seus dias como galhos ligados a um tronco. O tronco é Cristo. Sem essa ligação, seca.",
    reflexao: "O ramo não produz por esforço; produz por conexão. Se estou ligado a Cristo, o fruto vem no tempo certo. Se me desconecto, nem esforço resolve.",
    pergunta: "O que hoje pode te ajudar a permanecer ligado a Cristo?",
    oracao: "Jesus, permanece em mim. Faz-me permanecer em Ti. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O justo cairá sete vezes, e se levantará.",
    referencia: "Provérbios 24:16",
    dica: "Se você caiu esta semana, respire. A queda não te define; o levantar sim.",
    reflexao: "Ser justo não é nunca cair; é se recusar a ficar caído. Deus não conta minhas quedas; conta minhas voltas pra Ele.",
    pergunta: "Você tem se levantado ou tem ficado deitado onde caiu?",
    oracao: "Senhor, levanta-me de novo. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Sede fortes e corajosos! Não temais, nem vos espanteis; porque o Senhor vosso Deus é o que vai convosco.",
    referencia: "Deuteronômio 31:6",
    dica: "Respire profundo. Deus não está atrás; está indo junto.",
    reflexao: "A ordem é 'sede fortes', mas a razão é 'porque Ele vai contigo'. Coragem cristã não é confiança em mim; é confiança em Quem me acompanha.",
    pergunta: "Onde você precisa hoje agir com coragem, sabendo que não vai sozinho?",
    oracao: "Deus, obrigado por ir comigo. Fortalece-me. Em nome de Jesus, amém.",
  },
  {
    versiculo: "A tua palavra é lâmpada para os meus pés e luz para o meu caminho.",
    referencia: "Salmos 119:105",
    dica: "Antes de continuar, pense: onde na sua semana você precisou de luz e não tinha?",
    reflexao: "Lâmpada não ilumina o horizonte inteiro; ilumina o próximo passo. Deus não me mostra o mapa; me mostra o pé a pé. Meu papel é andar.",
    pergunta: "Qual próximo passo você precisa dar hoje, mesmo sem ver o resto do caminho?",
    oracao: "Senhor, ilumina o meu próximo passo. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Amarás o Senhor teu Deus de todo o teu coração, e ao teu próximo como a ti mesmo.",
    referencia: "Mateus 22:37-39",
    dica: "Pense em uma pessoa próxima. Pergunte a Deus: como eu posso amar essa pessoa hoje?",
    reflexao: "Toda a Lei cabe em duas palavras: ame Deus, ame gente. Não é técnica, é jeito de viver. E amar próximo começa em quem está fisicamente ao meu lado.",
    pergunta: "Quem você tem tido dificuldade de amar como Deus pede?",
    oracao: "Pai, ensina-me a amar como Tu amas. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Feliz o homem que não anda no conselho dos ímpios; antes tem seu prazer na lei do Senhor.",
    referencia: "Salmos 1:1-2",
    dica: "Pense: de qual voz você tem escutado mais essa semana? Deus, ou alguém que te afasta dEle?",
    reflexao: "As vozes que ouço mudam meu jeito de andar. O Salmo 1 mostra dois caminhos: um dá sombra e fruto, o outro seca. A escolha começa no ouvido.",
    pergunta: "Que voz você precisa silenciar essa semana pra ouvir Deus mais?",
    oracao: "Senhor, ensina-me a ter prazer na Tua Palavra. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Não te vingues, amados meus, mas dai lugar à ira de Deus.",
    referencia: "Romanos 12:19",
    dica: "Se alguém te machucou recentemente, respire e não pense em resposta. Só respire.",
    reflexao: "Vingança é peso que eu carrego pretendendo entregar pro outro. Deus me alivia disso: 'deixa comigo'. Confiar na justiça dEle liberta minhas mãos.",
    pergunta: "Quem hoje você precisa entregar pra Deus em vez de tentar acertar por conta?",
    oracao: "Senhor, entrego essa história nas Tuas mãos. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Aquele que começou a boa obra em vós há de completá-la.",
    referencia: "Filipenses 1:6",
    dica: "Lembre de um lugar onde você se sente 'em obra'. Deus não parou de trabalhar aí.",
    reflexao: "Deus não faz coisa pela metade. Se começou em mim, vai terminar. Meu papel é não desistir do processo. O prazo é dEle, o cuidado também.",
    pergunta: "Em qual área da sua vida você tem duvidado que Deus vai terminar?",
    oracao: "Pai, completa o que Tu começaste em mim. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Não vos conformeis com este mundo, mas transformai-vos pela renovação da vossa mente.",
    referencia: "Romanos 12:2",
    dica: "Feche os olhos por dez segundos. Pergunte: como está a minha mente hoje?",
    reflexao: "Deus não muda a vida quem só muda hábito; muda a vida quem muda pensamento. E pensamento se renova enchendo a mente do que é de Deus.",
    pergunta: "Que pensamento repetitivo em você precisa ser trocado pela verdade de Deus?",
    oracao: "Espírito Santo, renova a minha mente. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Bem-aventurados os pacificadores, porque serão chamados filhos de Deus.",
    referencia: "Mateus 5:9",
    dica: "Pense num conflito perto de você. Peça a Deus um gesto simples de paz hoje.",
    reflexao: "Pacificador não é quem foge de conflito; é quem carrega paz pra dentro dele. É trabalho ativo, de quem sabe que Deus é Pai e quer os filhos vivendo bem entre si.",
    pergunta: "Onde você pode ser pacificador esta semana?",
    oracao: "Deus da paz, faz de mim instrumento da Tua paz. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Buscai o Senhor enquanto se pode achar; invocai-o enquanto está perto.",
    referencia: "Isaías 55:6",
    dica: "Se você tem adiado buscar Deus, comece agora. Só agora, sem prometer nada.",
    reflexao: "Existe um agora que não volta. Buscar Deus é uma janela aberta hoje. Adiar é o modo mais silencioso de se afastar.",
    pergunta: "O que você tem adiado na sua vida com Deus?",
    oracao: "Senhor, eu Te busco. Estou aqui. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O reino de Deus não consiste em palavras, mas em poder.",
    referencia: "1 Coríntios 4:20",
    dica: "Pense num lugar em que você fala muito e age pouco. Nada de culpa; só nota.",
    reflexao: "Deus prefere um passo de obediência do que um discurso bonito. O Reino se vê no que a gente faz, não no que a gente promete.",
    pergunta: "Onde a sua fé precisa sair da boca pra ganhar as mãos?",
    oracao: "Senhor, dá-me pés e mãos que respondam ao que Tu ensinas. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Todo aquele que se exalta será humilhado; e todo aquele que se humilha será exaltado.",
    referencia: "Lucas 14:11",
    dica: "Respire e pergunte a si mesmo: onde eu tenho me exaltado sem perceber?",
    reflexao: "Deus resiste ao orgulhoso, mas se aproxima do humilde. Humildade não é se diminuir; é lembrar do lugar de Deus e do meu, sem inverter os dois.",
    pergunta: "Em qual relação você precisa se colocar em posição de escuta e não de razão?",
    oracao: "Pai, mantém-me humilde diante de Ti. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Cada um dê conforme propôs no coração; não com tristeza, ou por necessidade; porque Deus ama a quem dá com alegria.",
    referencia: "2 Coríntios 9:7",
    dica: "Pense em algo pequeno que você pode dar hoje: tempo, atenção, um recado.",
    reflexao: "Dar é um jeito de lembrar que nada é meu de verdade. Quem dá com alegria vive mais leve, porque não se agarra ao que tem.",
    pergunta: "O que você pode ofertar hoje, com alegria?",
    oracao: "Senhor, ensina-me a viver com as mãos abertas. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O que confia no Senhor é como uma árvore plantada junto às águas.",
    referencia: "Jeremias 17:7-8",
    dica: "Imagine seus pés como raízes profundas. Deus é a água que sustenta.",
    reflexao: "Árvore plantada junto às águas não teme o calor. A raiz alcança o que a superfície não vê. Confiar em Deus é enraizar em quem não seca.",
    pergunta: "Onde a sua raiz tem estado ultimamente?",
    oracao: "Senhor, enraíza a minha vida em Ti. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Ensinai-nos a contar os nossos dias, para que alcancemos coração sábio.",
    referencia: "Salmos 90:12",
    dica: "Pense: se restassem só 30 dias, o que ganharia mais atenção sua? Comece daí.",
    reflexao: "Contar os dias não é ficar triste; é ficar acordado. A vida cabe em decisões diárias. Quem lembra que o tempo passa vive melhor o que tem.",
    pergunta: "O que você tem adiado que já era pra ter feito?",
    oracao: "Senhor, ensina-me a viver este dia com intenção. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Portanto, não vos inquieteis pelo dia de amanhã.",
    referencia: "Mateus 6:34",
    dica: "Foque no que está diante de você hoje. Só isso.",
    reflexao: "Preocupação com o amanhã rouba a graça de hoje. Deus dá o pão de cada dia, não estoque semanal. Confiar é viver um por um.",
    pergunta: "Qual amanhã você tem carregado hoje sem precisar?",
    oracao: "Pai, dá-me graça pra viver só o hoje. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar.",
    referencia: "1 João 1:9",
    dica: "Não hesite. Deus não bate mais depois de você confessar. Ele perdoa.",
    reflexao: "Confissão é honestidade diante de Deus, não humilhação. Ele já sabe. Só espera eu dizer, pra restaurar. É o caminho mais curto pra paz.",
    pergunta: "O que você precisa colocar diante de Deus hoje, sem esconder?",
    oracao: "Pai, confesso o que Tu já conheces. Perdoa e restaura. Em nome de Jesus, amém.",
  },
  {
    versiculo: "O fruto do Espírito é amor, alegria, paz, longanimidade, benignidade, bondade, fé, mansidão e domínio próprio.",
    referencia: "Gálatas 5:22-23",
    dica: "Escolha um desses frutos e ore pedindo mais dele hoje.",
    reflexao: "Fruto não se produz apressado; nasce da árvore boa. Se o Espírito habita em mim, esses frutos vão aparecer no meu jeito, não como esforço, mas como consequência.",
    pergunta: "Qual desses frutos está mais escasso em você agora?",
    oracao: "Espírito Santo, produz esse fruto em mim. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Deus é amor.",
    referencia: "1 João 4:8",
    dica: "Repita a frase três vezes em silêncio. Deixe entrar.",
    reflexao: "Não é 'Deus tem amor', é 'Deus é amor'. Tudo o que Ele faz vem daí. Se estou em Deus, estou em amor. Se não sei amar, é porque preciso voltar pra fonte.",
    pergunta: "Você tem vivido a partir do amor de Deus ou tentando merecê-lo?",
    oracao: "Pai, eu me deixo amar por Ti hoje. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Sondai-me, ó Deus, e conhecei o meu coração; provai-me e conhecei os meus pensamentos.",
    referencia: "Salmos 139:23",
    dica: "Feche os olhos e permita que Deus olhe dentro sem se defender.",
    reflexao: "Pedir pra Deus me sondar é a oração dos que confiam. Ele não sonda pra condenar; sonda pra curar. Só cura o que a gente deixa Ele tocar.",
    pergunta: "Que canto do seu coração você tem escondido de Deus?",
    oracao: "Senhor, sonda-me e cura o que Tu encontrares. Em nome de Jesus, amém.",
  },
  {
    versiculo: "A minha paz vos dou; não vo-la dou como o mundo a dá.",
    referencia: "João 14:27",
    dica: "Respire lento por um minuto. A paz que Cristo dá não depende de circunstância.",
    reflexao: "Paz do mundo depende de tudo dar certo. Paz de Cristo não. Ela mora no meio da tempestade. É presença dEle, não ausência de problema.",
    pergunta: "Onde você precisa hoje da paz que só Cristo pode dar?",
    oracao: "Jesus, encho meu coração da Tua paz. Em nome de Jesus, amém.",
  },
  {
    versiculo: "Eu estou convosco todos os dias, até a consumação dos séculos.",
    referencia: "Mateus 28:20",
    dica: "Não precisa fazer nada agora. Só saiba: Ele está aqui.",
    reflexao: "Deus não é intermitente. Está em todos os dias, nos bons e nos ruins, nos silêncios e nos gritos. Nada me tira da presença dEle.",
    pergunta: "Como o seu dia seria diferente se você lembrasse disso o tempo todo?",
    oracao: "Jesus, obrigado por estar comigo hoje. Em nome de Jesus, amém.",
  },
];

function daySeed(): number {
  const d = new Date();
  return Number(
    `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}`,
  );
}

export function getDevocionalDoDia(): Devocional {
  return DEVOCIONAIS[daySeed() % DEVOCIONAIS.length];
}