export interface EtapaOracao {
  titulo: string;
  legenda: string;
  texto: string;
}

export interface SessaoOracao {
  id: string;
  tema: string;
  etapas: EtapaOracao[];
}

const L = {
  adorar: "Comece reconhecendo quem Deus é",
  agradecer: "Lembre-se do que Ele já fez",
  confessar: "Abra o coração com sinceridade",
  pedir: "Traga o que pesa em oração",
  entregar: "Solte tudo nas mãos dEle",
};

function s(id: string, tema: string, adorar: string, agradecer: string, confessar: string, pedir: string, entregar: string): SessaoOracao {
  return {
    id,
    tema,
    etapas: [
      { titulo: "Adorar", legenda: L.adorar, texto: adorar },
      { titulo: "Agradecer", legenda: L.agradecer, texto: agradecer },
      { titulo: "Confessar", legenda: L.confessar, texto: confessar },
      { titulo: "Pedir", legenda: L.pedir, texto: pedir },
      { titulo: "Entregar", legenda: L.entregar, texto: entregar },
    ],
  };
}

export const ORACOES_GUIADAS: SessaoOracao[] = [
  s("padrao", "Uma oração pra agora",
    "Senhor, Tu és santo e digno de toda honra. Antes de qualquer pedido, eu paro pra dizer: Tu és bom, e o Teu amor não muda.",
    "Obrigado, Pai, pela vida, pelo fôlego e pelas pessoas do meu caminho. Obrigado até pelo que ainda nem consigo perceber.",
    "Perdoa o que em mim não Te agrada, as palavras duras e os medos que me dominaram. Restaura o meu coração.",
    "Cuida do que me preocupa, dá sabedoria pras minhas decisões e paz onde a ansiedade quer entrar. Toca em quem eu amo.",
    "Solto o que não consigo carregar. Seja feita a Tua vontade, no Teu tempo. Confio em Ti. Em nome de Jesus, amém."),
  s("manha", "Ao começar o dia",
    "Bom dia, Senhor. Tu és o dono deste novo dia e nada foge do Teu controle.",
    "Obrigado pelo descanso da noite, pelo sol que nasceu e pela chance de recomeçar.",
    "Perdoa se eu chegar aqui já ansioso ou com pressa. Renova o que ficou pesado de ontem.",
    "Peço direção pras próximas horas, paz nas conversas e olho atento pra servir quem cruzar meu caminho.",
    "Este dia é Teu. Guia meus passos. Em nome de Jesus, amém."),
  s("noite", "Antes de dormir",
    "Senhor, Tu és o Deus que não dorme nem cochila e que guarda a minha vida.",
    "Obrigado por cada bênção deste dia, pelas alegrias e até pelo que me ensinou a confiar mais em Ti.",
    "Perdoa minhas palavras e atitudes que não Te honraram hoje.",
    "Peço descanso pro corpo, paz pra mente e cura pro que ficou dolorido.",
    "Entrego a noite em Tuas mãos. Renova minhas forças pro amanhã. Em nome de Jesus, amém."),
  s("ansiedade", "Quando a ansiedade aperta",
    "Deus da paz, Tu és maior do que tudo que me tira o chão. Contigo, o caos tem limite.",
    "Obrigado por já ter cuidado de tantas coisas que eu achei que não teriam saída.",
    "Confesso que quis controlar tudo sozinho e me esqueci de que Tu estás aqui.",
    "Aquieta o meu peito. Toma esse pensamento que não para. Coloca no lugar a Tua paz.",
    "Respiro fundo e entrego. O amanhã já é Teu. Em nome de Jesus, amém."),
  s("medo", "Quando o medo aparece",
    "Senhor, Tu és a minha luz e a minha salvação. A quem eu vou temer?",
    "Obrigado por já ter me tirado de tantos lugares escuros na vida.",
    "Confesso que às vezes o medo é maior do que a minha fé. Tem paciência de mim.",
    "Peço coragem pra dar o próximo passo, mesmo tremendo por dentro.",
    "Ando com Contigo. Vai na minha frente. Em nome de Jesus, amém."),
  s("tristeza", "Quando a tristeza pesa",
    "Pai, Tu és perto dos que têm o coração quebrantado. Sabes cada lágrima minha.",
    "Obrigado por não desviar o olhar quando eu chorei calado.",
    "Confesso o cansaço de fingir que estou bem quando não estou.",
    "Toca o que dói dentro de mim. Traz consolo que só vem de Ti.",
    "Descanso no Teu colo. Contigo, sei que amanhece. Em nome de Jesus, amém."),
  s("gratidao", "Só pra agradecer",
    "Senhor, Tu és bom, e a Tua bondade dura pra sempre.",
    "Obrigado pelo fôlego, pela minha família, pelo prato de comida e pela cama pra descansar. Obrigado pelas coisas simples que às vezes esqueço de ver.",
    "Perdoa quando reclamei do que devia ter agradecido.",
    "Ajuda-me a viver com o coração cheio e as mãos abertas.",
    "Toda glória é Tua. Em nome de Jesus, amém."),
  s("trabalho", "Antes do trabalho",
    "Senhor do céu e da terra, tudo o que existe é pra Tua glória.",
    "Obrigado pelo trabalho que tenho, pelas pessoas com quem convivo e pelo pão que ele traz pra mesa.",
    "Perdoa a pressa, o mau humor e as vezes em que quis passar por cima de alguém.",
    "Peço sabedoria pras decisões, paciência com quem me irrita e integridade em tudo que eu fizer.",
    "Trabalho como pra Ti. Prospera o que sair das minhas mãos. Em nome de Jesus, amém."),
  s("familia", "Pela família",
    "Pai, Tu és o Deus das famílias e o Autor do amor que nos une.",
    "Obrigado por cada pessoa que Tu colocaste debaixo deste teto.",
    "Perdoa as palavras que machucaram, o silêncio quando devíamos ter falado, e as expectativas que viraram cobrança.",
    "Cura as feridas antigas. Ensina a gente a se ouvir com carinho e a pedir desculpa sem orgulho.",
    "Coloco cada um deles em Tuas mãos. Cuida do meu lar. Em nome de Jesus, amém."),
  s("filhos", "Pelos meus filhos",
    "Senhor, Tu és Pai antes de mim e amas os meus filhos mais do que eu jamais poderia.",
    "Obrigado pela vida deles, pelos abraços, pelas perguntas difíceis e pelas risadas do meio do dia.",
    "Confesso minhas falhas como mãe/pai. Perdoa a impaciência e o mau exemplo.",
    "Guarda o coração deles. Levanta amizades boas. Faz deles pessoas que amam a Ti.",
    "Solto meus filhos nas Tuas mãos. Cuida do que eu não alcanço. Em nome de Jesus, amém."),
  s("saude", "Pela saúde",
    "Senhor, Tu és o Deus que cura e que sustenta o meu corpo.",
    "Obrigado por cada batida do coração, por cada respiração que veio sem eu pedir.",
    "Perdoa quando cuidei mal desse corpo que Tu me deste.",
    "Traz saúde pra onde há dor, força pra onde falta e paz pra onde o medo apertou.",
    "Meu corpo é Teu. Cura o que só Tu podes curar. Em nome de Jesus, amém."),
  s("financas", "Sobre dinheiro e contas",
    "Pai, Tu és o dono de tudo. O ouro e a prata são Teus.",
    "Obrigado pelo que já supriste e por não ter deixado faltar o essencial.",
    "Confesso a ansiedade com as contas e o hábito de gastar sem sabedoria.",
    "Peço provisão pra cada compromisso, sabedoria pra administrar e desapego do que não preciso.",
    "Entrego as minhas finanças. Ensina-me a confiar. Em nome de Jesus, amém."),
  s("decisao", "Antes de uma decisão",
    "Deus de toda sabedoria, Teu conselho é reto e a Tua vontade é boa.",
    "Obrigado pelas portas que já fechaste e pelas que abriste no tempo certo.",
    "Confesso a vontade de fazer do meu jeito, mesmo sem saber o fim.",
    "Dá-me clareza. Fecha o que não é pra mim. Abre só o que vem de Ti.",
    "Escolho Contigo. Guia meus próximos passos. Em nome de Jesus, amém."),
  s("perdoar", "Pra perdoar alguém",
    "Senhor justo, Tu conheces o que aconteceu comigo. Nada Te escapa.",
    "Obrigado por ter me perdoado tantas vezes sem cobrar nada em troca.",
    "Confesso a mágoa que ainda mora aqui e a vontade de revidar.",
    "Ajuda-me a soltar. Cura o que aquela pessoa feriu. Amolece o meu coração.",
    "Entrego essa história. A justiça é Tua. Em nome de Jesus, amém."),
  s("perdao", "Pra pedir perdão",
    "Pai santo, Tu és puro, e diante de Ti eu percebo o quanto errei.",
    "Obrigado por não me tratar segundo os meus pecados.",
    "Confesso, sem esconder: eu falhei. Pequei em pensamento, em palavra e em ação.",
    "Restaura o que quebrei. Ensina-me a reparar onde for possível.",
    "Sou Teu. Faz de mim de novo. Em nome de Jesus, amém."),
  s("solidao", "Quando bate a solidão",
    "Senhor, Tu prometeste nunca me deixar. Contigo eu nunca estou de fato só.",
    "Obrigado pelas amizades que já colocaste na minha vida, mesmo poucas.",
    "Confesso o vazio que sinto e a tentação de me isolar ainda mais.",
    "Enche esse silêncio com a Tua presença. Manda alguém pra me estender a mão.",
    "Descanso em Ti. Sou visto por Ti. Em nome de Jesus, amém."),
  s("raiva", "Quando estou com raiva",
    "Deus paciente, Tu és lento pra Te irar e grande em misericórdia.",
    "Obrigado por não me devolver na mesma medida em que eu explodo.",
    "Confesso a raiva que fervilha dentro de mim e a vontade de responder no impulso.",
    "Acalma o meu peito. Segura a minha língua. Ensina-me a esperar antes de reagir.",
    "Solto essa raiva. Não quero carregar. Em nome de Jesus, amém."),
  s("dividas", "Aliviar a mente das dívidas",
    "Senhor, Tu és o Provedor. Nada é impossível pra Ti.",
    "Obrigado por hoje ainda ter o que comer e um lugar pra dormir.",
    "Confesso a vergonha e a ansiedade que as dívidas trouxeram.",
    "Abre caminhos honestos de renda. Dá disciplina pra sair desse buraco.",
    "Coloco esse peso diante de Ti. Ando um passo por vez. Em nome de Jesus, amém."),
  s("relacionamento", "Sobre um relacionamento",
    "Deus de amor, Tu inventaste o amor e ninguém ama como Tu.",
    "Obrigado pelas pessoas que Tu colocaste ao meu lado até aqui.",
    "Confesso os medos, as inseguranças e a pressa em querer respostas.",
    "Guia o meu coração. Se for da Tua vontade, confirma. Se não for, tira a paz.",
    "Entrego esse vínculo. Só quero o que vem de Ti. Em nome de Jesus, amém."),
  s("casamento", "Pelo meu casamento",
    "Pai, Tu és quem uniu a gente e Tua aliança é firme.",
    "Obrigado pelo companheiro/a que Tu me deste, mesmo com todas as diferenças.",
    "Perdoa as palavras duras, o silêncio prolongado e as expectativas que viraram cobrança.",
    "Renova o carinho, a paciência e a admiração no nosso lar.",
    "Coloco o meu casamento em Tuas mãos. Restaura, Senhor. Em nome de Jesus, amém."),
  s("solteiro", "Sendo solteiro/a",
    "Senhor, Tu és tudo o que a minha alma precisa antes de qualquer outro amor.",
    "Obrigado pela vida que eu vivo hoje, com liberdade e tempo pra Te buscar.",
    "Confesso a ansiedade e a comparação com quem já casou.",
    "Ensina-me a viver o presente com plenitude. Prepara o meu coração no Teu tempo.",
    "Confio no Teu relógio. Ando com Contigo. Em nome de Jesus, amém."),
  s("perda", "Depois de uma perda",
    "Senhor da vida, só Tu compreendes o que é partir e permanecer.",
    "Obrigado pelos dias que tive com quem partiu. Cada memória é presente Teu.",
    "Confesso a raiva, a dúvida e a saudade que às vezes eu não sei onde colocar.",
    "Consola. Cura por dentro. Ensina-me a viver de novo, um passo por vez.",
    "Descanso no Teu peito. A vida ainda é Tua. Em nome de Jesus, amém."),
  s("desanimo", "Contra o desânimo",
    "Deus da esperança, Tu és a fonte que nunca seca.",
    "Obrigado pelas vezes em que Tu me ergueste sem que eu percebesse.",
    "Confesso o cansaço que me faz querer parar de tentar.",
    "Renova as minhas forças. Reacende o que apagou aqui dentro.",
    "Levanto de novo, pela Tua graça. Em nome de Jesus, amém."),
  s("vitoria", "Depois de uma vitória",
    "Senhor, Tua é a glória e o poder pra sempre.",
    "Obrigado pela conquista que veio das Tuas mãos, não das minhas forças.",
    "Confesso a tentação de me achar por causa disso.",
    "Guarda o meu coração da vaidade. Que eu use essa vitória pra Te honrar.",
    "Devolvo esse louvor pra Ti. Em nome de Jesus, amém."),
  s("derrota", "Depois de uma derrota",
    "Deus fiel, Tu não me abandonas quando eu tropeço.",
    "Obrigado por continuar do meu lado mesmo depois do que deu errado.",
    "Confesso a vergonha, a frustração e a vontade de desistir.",
    "Ensina-me o que eu preciso aprender aqui. Levanta-me quando for a hora.",
    "Solto o que passou. Sigo em frente Contigo. Em nome de Jesus, amém."),
  s("prova", "Antes de uma prova ou entrevista",
    "Senhor, Tu és o Deus da sabedoria e o dono das oportunidades.",
    "Obrigado por ter chegado até aqui, mesmo quando eu duvidei que chegaria.",
    "Confesso o nervosismo e o medo de não ser suficiente.",
    "Aquieta a minha mente. Traz à memória o que estudei. Dá clareza no que eu for falar.",
    "Faço a minha parte. O resultado é Teu. Em nome de Jesus, amém."),
  s("viagem", "Antes de uma viagem",
    "Senhor, Tu és o Deus que vai adiante e que também retaguarda.",
    "Obrigado pela oportunidade dessa viagem e por cada pessoa que vai comigo.",
    "Perdoa a pressa e a ansiedade dos preparativos.",
    "Guarda o caminho. Protege quem viaja, quem fica e o que deixamos pra trás.",
    "Vai na nossa frente. Confiamos em Ti. Em nome de Jesus, amém."),
  s("mudanca", "Passando por uma mudança",
    "Deus, Tu és o mesmo ontem, hoje e pra sempre, mesmo quando tudo à minha volta muda.",
    "Obrigado pelo que foi. Obrigado antes pelo que ainda vai vir.",
    "Confesso o medo do desconhecido e o apego ao que já passou.",
    "Dá-me coragem pra viver esse tempo novo. Ensina a soltar o que precisa ser solto.",
    "Ando pela fé. Contigo eu não caio. Em nome de Jesus, amém."),
  s("igreja", "Antes de ir à igreja",
    "Senhor, é bom vir até a Tua casa.",
    "Obrigado pela comunhão dos irmãos e pela Palavra que Tu tens pra hoje.",
    "Confesso as distrações e a mente cheia de coisas de fora.",
    "Prepara o meu coração pra ouvir. Fala Tu comigo hoje.",
    "Recebo o que Tu quiseres dizer. Em nome de Jesus, amém."),
  s("palavra", "Antes de ler a Bíblia",
    "Senhor, a Tua Palavra é lâmpada pros meus pés.",
    "Obrigado por falar comigo através da Bíblia até hoje.",
    "Confesso a preguiça e as vezes em que li sem ouvir de fato.",
    "Abre a minha compreensão. Aplica no meu coração o que eu precisar aprender.",
    "Fala, Senhor. Teu servo escuta. Em nome de Jesus, amém."),
  s("intercessao", "Por alguém especial",
    "Senhor, Tu conheces essa pessoa pelo nome e amas ela mais do que eu.",
    "Obrigado pelo que ela representa na minha vida.",
    "Confesso quando julguei em vez de orar por ela.",
    "Toca essa pessoa hoje. Cura o que dói. Salva o que só Tu podes salvar. Coloca pessoas boas ao lado dela.",
    "Entrego-a nas Tuas mãos. Faz o que só Tu podes. Em nome de Jesus, amém."),
  s("pais", "Pelos meus pais",
    "Pai, Tu és quem me deu a vida através deles.",
    "Obrigado pelo que já fizeram por mim, mesmo com todas as falhas.",
    "Perdoa as mágoas antigas e a distância que às vezes ficou.",
    "Cuida dos meus pais. Dá saúde, paz e a Tua salvação, se ainda faltar.",
    "Coloco eles em Tuas mãos. Cuida deles por mim. Em nome de Jesus, amém."),
  s("pais-inversao", "Pelos filhos que já cresceram",
    "Senhor, Tu és o Pai de todos os pais.",
    "Obrigado por cada um dos meus filhos, do jeito que são.",
    "Confesso quando quis controlar a vida deles em vez de confiá-los a Ti.",
    "Guarda-os onde a minha mão já não alcança. Protege as escolhas, os relacionamentos, o coração.",
    "Solto meus filhos. Cuida do que é Teu. Em nome de Jesus, amém."),
  s("amigos", "Pelos meus amigos",
    "Pai, o amigo é presente Teu na minha vida.",
    "Obrigado por cada pessoa que Tu colocaste como amiga verdadeira no meu caminho.",
    "Perdoa quando fui ausente ou negligente com quem esteve comigo.",
    "Abençoa cada um deles hoje. Cuida do que estão vivendo agora, do que nem me contam.",
    "Coloco os meus amigos em Tuas mãos. Em nome de Jesus, amém."),
  s("pais-idosos", "Cuidando de pais idosos",
    "Senhor, Tu prometeste sustentar até a velhice.",
    "Obrigado pela vida deles e por eu poder retribuir agora, mesmo cansado.",
    "Perdoa a impaciência e as vezes em que faltou carinho nas minhas palavras.",
    "Dá-me forças. Dá-lhes conforto. Cuida do corpo e da mente deles.",
    "Entrego essa fase nas Tuas mãos. Em nome de Jesus, amém."),
  s("gravida", "Esperando um filho",
    "Deus, Tu formaste essa vida no ventre.",
    "Obrigado pelo milagre que está acontecendo aqui dentro.",
    "Confesso o medo do parto, das mudanças, do futuro.",
    "Cuida dessa criança. Sustenta esse corpo. Prepara meu coração pra amar como Tu.",
    "Coloco esse bebê em Tuas mãos, antes mesmo de nascer. Em nome de Jesus, amém."),
  s("emprego", "Buscando um emprego",
    "Senhor, Tu és o Deus que abre e ninguém fecha.",
    "Obrigado por já ter suprido até agora, mesmo quando eu não sabia como seria o mês.",
    "Confesso a ansiedade, a vergonha e a comparação com quem já se colocou.",
    "Abre a porta certa. Faz meu currículo chegar onde deve chegar. Fecha o que não é pra mim.",
    "Faço a minha parte. Confio na Tua. Em nome de Jesus, amém."),
  s("estudos", "Nos estudos",
    "Senhor, Tu és a fonte do conhecimento e da sabedoria.",
    "Obrigado pela oportunidade de aprender e pelas pessoas que ensinam.",
    "Confesso a preguiça e as vezes em que estudei só pra passar.",
    "Dá-me disciplina, foco e memória. Que eu use o que aprendo pra bem.",
    "Coloco meus estudos diante de Ti. Em nome de Jesus, amém."),
  s("gravida-espera", "Tentando engravidar",
    "Senhor, Tu és o dono da vida.",
    "Obrigado por sonhar com a gente antes mesmo desse sonho nascer aqui.",
    "Confesso a dor de cada teste negativo e a raiva que às vezes bate.",
    "Se for da Tua vontade, abre esse ventre. Se ainda não for, sustenta o coração.",
    "Descanso em Ti. Teu tempo é perfeito. Em nome de Jesus, amém."),
  s("filho-longe", "Por um filho longe",
    "Pai, Tu vês onde ele/ela está agora.",
    "Obrigado por tê-lo protegido até aqui.",
    "Confesso as noites em que dormi chorando por saudade e medo.",
    "Cerca essa vida. Traz amizades boas. Guarda dos perigos que eu nem imagino.",
    "Solto meu filho nas Tuas mãos. Cuida por mim. Em nome de Jesus, amém."),
  s("vicio", "Contra um vício",
    "Senhor libertador, Tu és mais forte do que qualquer corrente.",
    "Obrigado pelas vezes em que Tu me livraste, mesmo quando eu voltei.",
    "Confesso a vergonha, a recaída, o cansaço de tentar sozinho.",
    "Quebra essa corrente. Manda gente pra me ajudar de perto. Restaura o que ele destruiu.",
    "Entrego essa luta. Tua é a batalha. Em nome de Jesus, amém."),
  s("noticia", "Depois de uma notícia difícil",
    "Senhor, Tu já sabias dessa notícia antes de eu ouvir.",
    "Obrigado por não me deixar sozinho pra receber isso.",
    "Confesso o medo, o choque e a raiva que me atravessou.",
    "Sustenta o meu coração. Dá clareza pros próximos passos. Cuida de quem foi atingido também.",
    "Descanso em Ti. Sei que Tu segues no controle. Em nome de Jesus, amém."),
  s("frustracao", "Quando nada deu certo",
    "Deus soberano, Tu vês além do meu plano.",
    "Obrigado porque nem tudo que eu quis Tu deste, e isso também foi cuidado.",
    "Confesso a frustração e a vontade de reclamar de Ti.",
    "Mostra o que eu preciso enxergar. Redireciona onde for necessário.",
    "Entrego meus planos. Faz-se a Tua vontade. Em nome de Jesus, amém."),
  s("aniversario", "No meu aniversário",
    "Senhor da minha vida, Tu és o autor da minha história.",
    "Obrigado por mais um ano. Por cada pessoa, cada aprendizado e cada livramento.",
    "Confesso o que fiz de errado no ano que passou.",
    "Escreve esse próximo ciclo Contigo. Ensina-me a viver o que ainda tenho pela frente.",
    "Consagro esse novo ano a Ti. Em nome de Jesus, amém."),
  s("comida", "Antes da refeição",
    "Pai bondoso, Tu és quem sustenta toda vida.",
    "Obrigado pelo alimento sobre esta mesa e por quem trabalhou pra que ele chegasse aqui.",
    "Perdoa quando esqueço que tudo vem de Ti.",
    "Que não falte o pão a quem tem fome. Nutre também o meu espírito Contigo.",
    "Recebo esse alimento com gratidão. Em nome de Jesus, amém."),
  s("silencio", "Só pra ficar em silêncio",
    "Senhor, Tu falas no sussurro suave. Aquieta-me.",
    "Obrigado por me convidar pra parar em vez de correr.",
    "Confesso a mente cheia e a pressa de sempre.",
    "Aquieta o meu coração. Ensina-me a ouvir.",
    "Fica comigo neste silêncio. Em nome de Jesus, amém."),
  s("cansaco", "Quando estou exausto",
    "Senhor, Tu és o Deus que dá descanso.",
    "Obrigado por me sustentar mesmo quando eu não sei mais como continuar.",
    "Confesso que tentei fazer sozinho o que era pra ser feito Contigo.",
    "Renova as minhas forças. Recolhe o que ficou esparramado dentro de mim.",
    "Descanso em Ti. Contigo eu recomeço. Em nome de Jesus, amém."),
  s("nova-semana", "Começando a semana",
    "Senhor, Tu és o dono do meu tempo e das minhas semanas.",
    "Obrigado pelo descanso que veio e pela chance de recomeçar.",
    "Perdoa o mau humor de segunda e a vontade de que a semana já acabasse.",
    "Guia cada dia dela. Dá foco, disciplina e presença nas coisas que importam.",
    "Consagro essa semana a Ti. Em nome de Jesus, amém."),
  s("gratidao-simples", "Gratidão simples",
    "Deus meu, Tu és bom só por ser quem és.",
    "Obrigado pelo café da manhã, pelo abraço, pela música que tocou e me lembrou de Ti.",
    "Perdoa quando eu vivo no automático e passo por Ti sem ver.",
    "Abre os meus olhos pras pequenas bênçãos hoje.",
    "Recebo o que Tu me dás. Em nome de Jesus, amém."),
  s("chamado", "Sobre um chamado",
    "Senhor, Tu chamas, capacita e envia.",
    "Obrigado por não desistir de mim quando eu mesmo já tinha desistido.",
    "Confesso o medo de não dar conta e a vergonha de dizer sim.",
    "Confirma o que é de Ti. Fecha o que não é. Dá coragem pra andar quando for a hora.",
    "Aqui estou. Envia-me se for da Tua vontade. Em nome de Jesus, amém."),
];

export function getSessaoAleatoria(excluir?: string): SessaoOracao {
  const pool = excluir ? ORACOES_GUIADAS.filter((s) => s.id !== excluir) : ORACOES_GUIADAS;
  return pool[Math.floor(Math.random() * pool.length)];
}