// Pool de frases curtas de oração — feitas pra caber em widget nativo
// (iOS lock screen / Android home) em 2-3 linhas. Formato: primeira pessoa,
// tom de conversa com Deus, sem citações bíblicas longas.
// Reaproveitável em notificações e no endpoint /api/public/widget-messages.

export type OracaoCurta = { ref: string; text: string };

export const ORACOES_CURTAS: OracaoCurta[] = [
  { ref: "Oração", text: "Senhor, hoje eu confio em Ti. Cuida do que eu não dou conta." },
  { ref: "Oração", text: "Pai, obrigado pelo respirar deste momento." },
  { ref: "Oração", text: "Jesus, entrego este dia nas Tuas mãos." },
  { ref: "Oração", text: "Espírito Santo, guia meus passos agora." },
  { ref: "Oração", text: "Senhor, aquieta meu coração e me dá paz." },
  { ref: "Oração", text: "Pai, me ensina a descansar em Ti." },
  { ref: "Oração", text: "Deus, renova minhas forças. Estou cansado(a)." },
  { ref: "Oração", text: "Senhor, cuida das pessoas que amo hoje." },
  { ref: "Oração", text: "Pai, obrigado por tudo o que já fizeste por mim." },
  { ref: "Oração", text: "Jesus, me ajuda a perdoar quem me feriu." },
  { ref: "Oração", text: "Senhor, me livra do medo. Estou contigo." },
  { ref: "Oração", text: "Pai, faça em mim segundo a Tua vontade." },
  { ref: "Oração", text: "Deus, me dá sabedoria para as escolhas de hoje." },
  { ref: "Oração", text: "Senhor, cura o que dói dentro de mim." },
  { ref: "Oração", text: "Pai, obrigado por nunca me abandonar." },
  { ref: "Oração", text: "Jesus, seja o Senhor da minha vida hoje." },
  { ref: "Oração", text: "Espírito Santo, me enche da Tua paz." },
  { ref: "Oração", text: "Senhor, transforma minha ansiedade em confiança." },
  { ref: "Oração", text: "Pai, obrigado pela nova manhã que Tu me dás." },
  { ref: "Oração", text: "Deus, guarda minha mente e meu coração." },
  { ref: "Oração", text: "Senhor, me ensina a amar como Tu amas." },
  { ref: "Oração", text: "Pai, me ajuda a começar de novo." },
  { ref: "Oração", text: "Jesus, obrigado pela Tua cruz e Tua graça." },
  { ref: "Oração", text: "Senhor, me faz instrumento da Tua paz." },
  { ref: "Oração", text: "Pai, ilumina o caminho que devo seguir." },
  { ref: "Oração", text: "Deus, coloca em mim um coração grato." },
  { ref: "Oração", text: "Senhor, cuida da minha família neste dia." },
  { ref: "Oração", text: "Pai, me ajuda a confiar quando não entendo." },
  { ref: "Oração", text: "Jesus, estou aqui. Fala comigo, eu preciso." },
  { ref: "Oração", text: "Espírito Santo, sopra vida onde há cansaço." },
  { ref: "Oração", text: "Senhor, tira de mim o peso que não é meu." },
  { ref: "Oração", text: "Pai, obrigado por me chamar de filho(a) Teu(a)." },
  { ref: "Oração", text: "Deus, me ajuda a ver o bem que ainda existe." },
  { ref: "Oração", text: "Senhor, faça de mim uma pessoa melhor hoje." },
  { ref: "Oração", text: "Pai, sara as feridas que ninguém enxerga." },
  { ref: "Oração", text: "Jesus, me guarda de todo mal neste dia." },
  { ref: "Oração", text: "Senhor, obrigado pela vida que me deste." },
  { ref: "Oração", text: "Pai, coloca paz onde há conflito em mim." },
  { ref: "Oração", text: "Deus, me lembra de quem eu sou em Ti." },
  { ref: "Oração", text: "Senhor, aumenta a minha fé. Sozinho(a) eu não consigo." },
  { ref: "Oração", text: "Pai, me ensina a esperar no Teu tempo." },
  { ref: "Oração", text: "Jesus, sê a luz nos meus dias difíceis." },
  { ref: "Oração", text: "Espírito Santo, consola meu coração agora." },
  { ref: "Oração", text: "Senhor, obrigado pelas pequenas alegrias de hoje." },
  { ref: "Oração", text: "Pai, me livra da pressa e da agitação." },
  { ref: "Oração", text: "Deus, cuida do amanhã que ainda me assusta." },
  { ref: "Oração", text: "Senhor, faz o que só Tu podes fazer em mim." },
  { ref: "Oração", text: "Pai, obrigado por ouvir a minha voz." },
  { ref: "Oração", text: "Jesus, seja o refúgio da minha alma." },
  { ref: "Oração", text: "Senhor, me dá coragem para continuar." },
  { ref: "Oração", text: "Pai, abençoa quem cruzar meu caminho hoje." },
  { ref: "Oração", text: "Deus, obrigado pelo Teu amor que não falha." },
  { ref: "Oração", text: "Senhor, me ajuda a soltar o que preciso soltar." },
  { ref: "Oração", text: "Pai, restaura o que se quebrou em mim." },
  { ref: "Oração", text: "Jesus, obrigado por caminhar comigo." },
  { ref: "Oração", text: "Espírito Santo, me ensina a orar quando faltam palavras." },
  { ref: "Oração", text: "Senhor, aqui estou. Faz de mim o que Tu quiseres." },
  { ref: "Oração", text: "Pai, cuida do meu sono e do meu descanso." },
  { ref: "Oração", text: "Deus, obrigado pela graça deste instante." },
  { ref: "Oração", text: "Senhor, seja a força quando a minha acabar." },
  { ref: "Oração", text: "Pai, coloca em mim vontade de recomeçar." },
  { ref: "Oração", text: "Jesus, ensina meu coração a ser manso." },
  { ref: "Oração", text: "Senhor, obrigado por estar comigo mesmo no silêncio." },
  { ref: "Oração", text: "Pai, me ajuda a confiar mais do que temer." },
  { ref: "Oração", text: "Deus, transforma esta oração em milagre." },
  { ref: "Oração", text: "Senhor, obrigado pela esperança que Tu renovas." },
  { ref: "Oração", text: "Pai, seja feita a Tua vontade, não a minha." },
  { ref: "Oração", text: "Jesus, quero Te seguir mesmo quando dói." },
  { ref: "Oração", text: "Espírito Santo, guarda meu coração da amargura." },
  { ref: "Oração", text: "Senhor, obrigado pela paz que só Tu podes dar." },
  { ref: "Oração", text: "Pai, me faz enxergar o próximo com Teus olhos." },
  { ref: "Oração", text: "Deus, ampara quem hoje se sente sozinho(a)." },
  { ref: "Oração", text: "Senhor, me tira do medo e me coloca na fé." },
  { ref: "Oração", text: "Pai, obrigado por tudo o que ainda vou viver contigo." },
];