// Conteúdo bíblico/conforto para notificações horárias e card "Escolhida agora"
export type ChosenItem = {
  ref: string;
  text: string;
};

export const PSALMS: ChosenItem[] = [
  { ref: "Salmo 23:1", text: "O Senhor é o meu pastor; nada me faltará." },
  { ref: "Salmo 27:1", text: "O Senhor é a minha luz e a minha salvação; a quem temerei?" },
  { ref: "Salmo 34:18", text: "Perto está o Senhor dos que têm o coração quebrantado." },
  { ref: "Salmo 46:1", text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." },
  { ref: "Salmo 46:10", text: "Aquietai-vos e sabei que eu sou Deus." },
  { ref: "Salmo 91:1", text: "Aquele que habita no esconderijo do Altíssimo descansará à sombra do Onipotente." },
  { ref: "Salmo 91:11", text: "Aos seus anjos dará ordens a teu respeito, para te guardarem em todos os teus caminhos." },
  { ref: "Salmo 121:1-2", text: "Elevo os meus olhos para os montes; de onde virá o meu socorro? O meu socorro vem do Senhor." },
  { ref: "Salmo 139:7", text: "Para onde me irei do teu Espírito? Para onde fugirei da tua face?" },
  { ref: "Salmo 143:8", text: "Faze-me ouvir pela manhã a tua benignidade, pois em ti confio." },
  { ref: "Salmo 119:105", text: "Lâmpada para os meus pés é tua palavra, e luz para o meu caminho." },
  { ref: "Salmo 16:11", text: "Tu me farás ver os caminhos da vida; na tua presença há plenitude de alegria." },
  { ref: "Salmo 37:4", text: "Deleita-te no Senhor, e ele te concederá o que deseja o teu coração." },
  { ref: "Salmo 56:3", text: "Em qualquer tempo em que eu temer, hei de confiar em ti." },
  { ref: "Salmo 62:1", text: "Somente em Deus, ó minha alma, espera silenciosa; dele vem a minha salvação." },
  { ref: "Salmo 73:26", text: "Deus é a fortaleza do meu coração e a minha porção para sempre." },
  { ref: "Filipenses 4:7", text: "A paz de Deus, que excede todo o entendimento, guardará o vosso coração." },
  { ref: "Isaías 41:10", text: "Não temas, porque eu sou contigo; eu te fortaleço e te ajudo." },
  { ref: "Mateus 11:28", text: "Vinde a mim, todos os que estais cansados, e eu vos aliviarei." },
  { ref: "João 14:27", text: "Deixo-vos a paz, a minha paz vos dou; não se turbe o vosso coração." },
  { ref: "Romanos 8:28", text: "Todas as coisas cooperam para o bem daqueles que amam a Deus." },
  { ref: "2 Coríntios 12:9", text: "A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza." },
  { ref: "Provérbios 3:5", text: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento." },
  { ref: "Lamentações 3:22-23", text: "As misericórdias do Senhor são novas a cada manhã; grande é a tua fidelidade." },
  { ref: "Salmo 3:3", text: "Mas tu, Senhor, és o escudo que me protege, és a minha glória e o que me faz andar de cabeça erguida." },
  { ref: "Salmo 18:2", text: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador." },
  { ref: "Salmo 19:14", text: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração diante de ti, Senhor." },
  { ref: "Salmo 25:4-5", text: "Faze-me, Senhor, conhecer os teus caminhos; ensina-me as tuas veredas." },
  { ref: "Salmo 30:5", text: "O choro pode durar uma noite, mas a alegria vem pela manhã." },
  { ref: "Salmo 31:24", text: "Sede fortes, e revigore-se o vosso coração, vós todos que esperais no Senhor." },
  { ref: "Salmo 32:8", text: "Eu te instruirei e te ensinarei o caminho que deves seguir; aconselhar-te-ei, tendo-te sob a minha vista." },
  { ref: "Salmo 34:8", text: "Provai e vede que o Senhor é bom; bem-aventurado o homem que nele se refugia." },
  { ref: "Salmo 40:1", text: "Esperei com paciência no Senhor, e ele se inclinou para mim e ouviu o meu clamor." },
  { ref: "Salmo 42:11", text: "Por que estás abatida, ó minha alma? Espera em Deus, pois ainda o louvarei." },
  { ref: "Salmo 51:10", text: "Cria em mim, ó Deus, um coração puro e renova dentro de mim um espírito reto." },
  { ref: "Salmo 55:22", text: "Lança o teu cuidado sobre o Senhor, e ele te susterá." },
  { ref: "Salmo 63:1", text: "Ó Deus, tu és o meu Deus; eu te buscarei de madrugada; a minha alma tem sede de ti." },
  { ref: "Salmo 84:11", text: "Pois o Senhor Deus é sol e escudo; ele dá graça e glória." },
  { ref: "Salmo 86:5", text: "Pois tu, Senhor, és bom, e pronto a perdoar, e abundante em benignidade." },
  { ref: "Salmo 90:12", text: "Ensina-nos a contar os nossos dias, para que alcancemos coração sábio." },
  { ref: "Salmo 91:2", text: "Direi do Senhor: Ele é o meu refúgio e a minha fortaleza, o meu Deus em quem confio." },
  { ref: "Salmo 100:5", text: "Porque o Senhor é bom, a sua misericórdia dura para sempre, e a sua fidelidade, de geração em geração." },
  { ref: "Salmo 103:2-3", text: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum dos seus benefícios." },
  { ref: "Salmo 116:7", text: "Volta, minha alma, ao teu repouso, pois o Senhor te fez bem." },
  { ref: "Salmo 118:24", text: "Este é o dia que fez o Senhor; regozijemo-nos e alegremo-nos nele." },
  { ref: "Salmo 127:1", text: "Se o Senhor não edificar a casa, em vão trabalham os que a edificam." },
  { ref: "Salmo 130:5", text: "Aguardo o Senhor; a minha alma o aguarda, e espero na sua palavra." },
  { ref: "Salmo 133:1", text: "Oh! quão bom e quão suave é que os irmãos vivam em união!" },
  { ref: "Salmo 138:8", text: "O Senhor aperfeiçoará o que me concerne; a tua benignidade, Senhor, dura para sempre." },
  { ref: "Salmo 145:18", text: "Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade." },
  { ref: "Salmo 147:3", text: "Sara os de coração quebrantado e cura-lhes as feridas." },
  { ref: "Salmo 150:6", text: "Todo ser que respira louve ao Senhor. Aleluia!" },
  { ref: "Isaías 26:3", text: "Tu, Senhor, conservarás em perfeita paz aquele cujo propósito é firme; porque ele confia em ti." },
  { ref: "Isaías 40:31", text: "Mas os que esperam no Senhor renovam as suas forças; sobem com asas como águias." },
  { ref: "Isaías 43:2", text: "Quando passares pelas águas, eu serei contigo; quando pelos rios, eles não te submergirão." },
  { ref: "Isaías 55:8-9", text: "Os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos." },
  { ref: "Jeremias 29:11", text: "Eu sei os planos que tenho para vocês: planos de paz, e não de mal, para dar-lhes um futuro e uma esperança." },
  { ref: "Jeremias 31:3", text: "Com amor eterno eu te amei; por isso, com amor leal te atraí." },
  { ref: "Sofonias 3:17", text: "O Senhor, teu Deus, está no meio de ti, poderoso para te salvar; ele se alegrará por ti com cânticos." },
  { ref: "Mateus 5:6", text: "Bem-aventurados os que têm fome e sede de justiça, porque serão fartos." },
  { ref: "Mateus 6:33", text: "Buscai, pois, em primeiro lugar, o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas." },
  { ref: "Mateus 11:29", text: "Tomai sobre vós o meu jugo e aprendei de mim, porque sou manso e humilde de coração." },
  { ref: "Marcos 9:23", text: "Tudo é possível ao que crê." },
  { ref: "Lucas 1:37", text: "Para Deus nada é impossível." },
  { ref: "João 3:16", text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito." },
  { ref: "João 8:12", text: "Eu sou a luz do mundo; quem me segue não andará nas trevas, mas terá a luz da vida." },
  { ref: "João 15:5", text: "Eu sou a videira, vós, os ramos. Quem permanece em mim, e eu, nele, esse dá muito fruto." },
  { ref: "João 16:33", text: "No mundo, passais por aflições; mas tende bom ânimo: eu venci o mundo." },
  { ref: "Atos 1:8", text: "Mas recebereis poder, ao descer sobre vós o Espírito Santo." },
  { ref: "Romanos 5:5", text: "A esperança não nos decepciona, porque o amor de Deus foi derramado em nosso coração." },
  { ref: "Romanos 8:31", text: "Se Deus é por nós, quem será contra nós?" },
  { ref: "Romanos 12:12", text: "Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração." },
  { ref: "Romanos 15:13", text: "O Deus da esperança vos encha de toda a alegria e paz no vosso crer." },
  { ref: "1 Coríntios 13:4", text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha." },
  { ref: "1 Coríntios 16:13", text: "Vigiai, estai firmes na fé, portai-vos varonilmente, fortalecei-vos." },
  { ref: "2 Coríntios 5:17", text: "Se alguém está em Cristo, é nova criação; as coisas antigas já passaram; eis que se fizeram novas." },
  { ref: "Gálatas 5:22", text: "O fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade." },
  { ref: "Efésios 2:8", text: "Pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus." },
  { ref: "Efésios 3:20", text: "Àquele que é poderoso para fazer infinitamente mais do que tudo quanto pedimos ou pensamos." },
  { ref: "Filipenses 1:6", text: "Aquele que começou boa obra em vós há de completá-la até o Dia de Cristo Jesus." },
  { ref: "Filipenses 4:4", text: "Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos." },
  { ref: "Filipenses 4:13", text: "Tudo posso naquele que me fortalece." },
  { ref: "Colossenses 3:15", text: "Seja a paz de Cristo o árbitro em vosso coração; sede agradecidos." },
  { ref: "1 Tessalonicenses 5:16-18", text: "Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças." },
  { ref: "2 Timóteo 1:7", text: "Porque Deus não nos tem dado espírito de covardia, mas de poder, de amor e de moderação." },
  { ref: "Hebreus 11:1", text: "Ora, a fé é a certeza de coisas que se esperam, a convicção de fatos que se não veem." },
  { ref: "Hebreus 13:5", text: "De modo nenhum te deixarei, nunca jamais te abandonarei." },
  { ref: "Tiago 1:5", text: "Se algum de vós necessita de sabedoria, peça-a a Deus, que a todos dá liberalmente." },
  { ref: "1 Pedro 5:7", text: "Lançai sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós." },
  { ref: "1 João 4:18", text: "No amor não existe medo; antes, o perfeito amor lança fora o medo." },
  { ref: "Apocalipse 21:4", text: "Ele lhes enxugará dos olhos toda lágrima; e a morte já não existirá." },
  { ref: "Provérbios 16:3", text: "Confia ao Senhor as tuas obras, e os teus planos serão bem-sucedidos." },
  { ref: "Provérbios 18:10", text: "Torre forte é o nome do Senhor; para ela corre o justo e está seguro." },
  { ref: "Eclesiastes 3:1", text: "Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu." },
  { ref: "Miquéias 6:8", text: "Pratica a justiça, ama a misericórdia e anda humildemente com o teu Deus." },
  { ref: "Naum 1:7", text: "O Senhor é bom, é fortaleza no dia da angústia, e conhece os que nele se refugiam." },
  { ref: "Êxodo 14:14", text: "O Senhor pelejará por vós, e vós vos calareis." },
  { ref: "Josué 1:9", text: "Sê forte e corajoso; não temas, nem te espantes, porque o Senhor está contigo." },
  { ref: "1 Crônicas 16:11", text: "Buscai ao Senhor e o seu poder; buscai a sua face continuamente." },
];

// Seleção determinística por hora — todos veem a "mesma escolhida" naquela hora.
export function getChosenForHour(date = new Date()): ChosenItem {
  const key = Math.floor(date.getTime() / (60 * 60 * 1000));
  return PSALMS[key % PSALMS.length];
}

export function getChosenRandom(): ChosenItem {
  return PSALMS[Math.floor(Math.random() * PSALMS.length)];
}

export const NOTIFICATION_TITLES = [
  "Essa foi escolhida para você",
  "Uma palavra para agora",
  "CHOSEN — para o seu momento",
  "Pausa para a alma",
  "Respire e leia",
  "Uma luz para o seu caminho",
  "Deus tem algo para você",
  "Respire fundo e ouça",
  "Tempo de descansar nEle",
  "Uma promessa para hoje",
  "Para o seu coração agora",
  "Pare por um instante",
  "Você foi lembrado(a)",
  "Palavra do Pai para você",
  "Um sopro de paz",
  "Lembre-se de quem te ama",
  "Pequena pausa, grande verdade",
  "Hoje, isso é para você",
  "Recarregue a alma",
];

export const QUIET_HOURS = { start: 8, end: 22 } as const;

export function isWithinQuietHours(date = new Date()): boolean {
  const h = date.getHours();
  return h >= QUIET_HOURS.start && h < QUIET_HOURS.end;
}
