/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SilencioRouteImport } from './routes/silencio'
import { Route as OracoesRouteImport } from './routes/oracoes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPayloadRouteImport } from './routes/p.$payload'
import { Route as MensagemSentimentoRouteImport } from './routes/mensagem/$sentimento'

const SilencioRoute = SilencioRouteImport.update({
  id: '/silencio',
  path: '/silencio',
  getParentRoute: () => rootRouteImport,
} as any)
const OracoesRoute = OracoesRouteImport.update({
  id: '/oracoes',
  path: '/oracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPayloadRoute = PPayloadRouteImport.update({
  id: '/p/$payload',
  path: '/p/$payload',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagemSentimentoRoute = MensagemSentimentoRouteImport.update({
  id: '/mensagem/$sentimento',
  path: '/mensagem/$sentimento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/oracoes': typeof OracoesRoute
  '/silencio': typeof SilencioRoute
  '/mensagem/$sentimento': typeof MensagemSentimentoRoute
  '/p/$payload': typeof PPayloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/oracoes': typeof OracoesRoute
  '/silencio': typeof SilencioRoute
  '/mensagem/$sentimento': typeof MensagemSentimentoRoute
  '/p/$payload': typeof PPayloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/oracoes': typeof OracoesRoute
  '/silencio': typeof SilencioRoute
  '/mensagem/$sentimento': typeof MensagemSentimentoRoute
  '/p/$payload': typeof PPayloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboarding'
    | '/oracoes'
    | '/silencio'
    | '/mensagem/$sentimento'
    | '/p/$payload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboarding'
    | '/oracoes'
    | '/silencio'
    | '/mensagem/$sentimento'
    | '/p/$payload'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboarding'
    | '/oracoes'
    | '/silencio'
    | '/mensagem/$sentimento'
    | '/p/$payload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  OracoesRoute: typeof OracoesRoute
  SilencioRoute: typeof SilencioRoute
  MensagemSentimentoRoute: typeof MensagemSentimentoRoute
  PPayloadRoute: typeof PPayloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/silencio': {
      id: '/silencio'
      path: '/silencio'
      fullPath: '/silencio'
      preLoaderRoute: typeof SilencioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracoes': {
      id: '/oracoes'
      path: '/oracoes'
      fullPath: '/oracoes'
      preLoaderRoute: typeof OracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$payload': {
      id: '/p/$payload'
      path: '/p/$payload'
      fullPath: '/p/$payload'
      preLoaderRoute: typeof PPayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagem/$sentimento': {
      id: '/mensagem/$sentimento'
      path: '/mensagem/$sentimento'
      fullPath: '/mensagem/$sentimento'
      preLoaderRoute: typeof MensagemSentimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  OracoesRoute: OracoesRoute,
  SilencioRoute: SilencioRoute,
  MensagemSentimentoRoute: MensagemSentimentoRoute,
  PPayloadRoute: PPayloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
